### ISSUE TITLE
Issues with new AudioCapture implementation

### ISSUE THREAD

**Issue by glopesdev** [opentk/opentk#1007]
The new `AudioCapture` class in OpenTK 4.0 is a generic class with an `unsafe` constructor. This makes it surprisingly tedious to instantiate the class.

First, having a generic constraint be an `Enum` is slightly unconventional and confusing to the consumer. Is there anything to be gained by this? Can any `AudioCapture` implementation support anything other than the values specified in `BufferFormat`?

Removing the `unsafe` keyword seems to be a matter of encapsulating the private handle assignment inside an `unsafe` block so that this doesn't have to bubble up to the consumer.

Furthermore, this class has a declared finalizer, but fails to call `GC.SuppressFinalize(this)` in the `Dispose` method. This creates an unnecessary performance issue, as finalizer code is still called by GC.

Finally, I propose the `AudioCapture` class and its associated classes be grouped into the core assembly and namespace, as it is an integral part of OpenAL and *must* be available in every implementation, [as per the specs](https://github.com/openalext/openalext/blob/master/ALC_EXT_CAPTURE.txt).

**Comment by varon** [comment]
This is something we'd probably have to address in 5.x

**Comment by NogginBops** [comment]
This is fixed in the released version of the `OpenAL` part of OpenTK 4.0. 
All OpenAL functions should be accessible without an unsafe context.

The specific class `AudioCapture`  mentioned in this issue no longer exists. There is no replacement for it, but `ALCaptureDevice` and manual OpenAL calls can be used to achieve the same result.
