### ISSUE TITLE
Setting IsFullscreen on NativeWindowSettings seems to have no influence

### ISSUE THREAD

**Issue by G43beli** [opentk/opentk#1067]
### Description

In OpenTK 4, setting IsFullscreen on NativeWindowSettings seems to have no influence. If isFullscreen is set to true, the window does still stay in its default location and size.

IsFullscreen exists as a property. But is never used anywhere in the window creation.

### Repro steps

1. Creating class Window in Console App:
```csharp
public class Window : GameWindow
    {
        public Window(string title) : base(GameWindowSettings.Default, CreateNativeWindowSettings(title))
        { }

        private unsafe static NativeWindowSettings CreateNativeWindowSettings(string title)
        {
            var nativeWindowSettings = new NativeWindowSettings
            {
                IsFullscreen = true,
                Title = title
            };

            return nativeWindowSettings;
        }
}
```

2. Start it from Main method 

```csharp
private static void Main(string[] args)
{
            using (var window = new Window("Test Window"))
            {
                window.Run();
            }
}
```

### Expected behavior

Window opens in Fullscreen.

### Actual behavior

Window still opens with default size. If custom size is provided, the custom size is taken, but IsFullscreen still is ignored.

### Related information 

* Win 10
* OpenTK 4.0.0-pre9.1 from nuget
* .Net core 3.1

**Comment by varon** [comment]
Should be fixed in 4.3.0

**Comment by NogginBops** [comment]
It seems like this is not in-fact fixed in 4.3.0 as this issue still exists in 4.4.0.

The workaround is to use the `WindowState` property instead.

**Comment by seanofw** [comment]
It looks like when I rewrote a bunch of the window-state code last fall, I didn't even notice that there was an `IsFullscreen` property on `NativeWindowSettings`:  Everything initialization-related is handled exclusively through the `WindowState` property.

But since this can be handled through `WindowState`, do we even still want `IsFullscreen` as part of `NativeWindowSettings`, since `WindowState` can completely cover it?  Having the initialization `IsFullscreen` property makes for nice parity with the `NativeWindow.IsFullscreen` property, but it's not really necessary.  But if we still want to keep it for backwards-compatibility, maybe we should change it to just be a simple proxy property for assigning a specific value to `WindowState`, something like

```c#
public bool IsFullscreen
{
    get => WindowState == WindowState.Fullscreen;
    set => WindowState = value ? WindowState.Fullscreen : WindowState.Normal;
}
```

What do you think, @NogginBops and @varon ?

**Comment by NogginBops** [comment]
I think we should remove `IsFullscreen` from the settings completely and have people use `WindowState` only.
Making it a property like that will only lead to confusion in the long run.

**Comment by seanofw** [comment]
So maybe we adjust the innards of `NativeWindow` to treat it as an override instead, then, something like

```c#
WindowState initialState = nativeWindowSettings.IsFullscreen
    ? WindowState.Fullscreen
    : nativeWindowSettings.WindowState;
...
```

That behavior is slightly less confusing than the dueling properties might be in the prior suggestion.

Anyway, the only reason I'd suggest keeping it is because `NativeWindow` itself has an `IsFullscreen` property, so it makes sense to either keep both or get rid of both.  And there might be a lot of code out there that uses at least one of them, so I'd suggest keeping both, and making them both _work_, is probably the right course of action.

**Comment by NogginBops** [comment]
There is no way to set the `IsFullscreen` property of `NativeWindow` as it's a read only property.
So it's illogical to expect `NativeWindowSettings` to have a setting for it in the same way.

Removing it seems like the only reasonable action to me.
