### ISSUE TITLE
OpenTK4 GL Context Started on Update thread when IsMultiThreaded true

### ISSUE THREAD

**Issue by voltairianman** [opentk/opentk#1075]
### Description

The GL Context seems to always be created on the main update thread, regardless of whether there is a separate render thread started via isMultiThreaded.

### Repro steps
This simple example reproduces the issue.
```
static void Main(string[] args)
        {
            GameWindow gameWindow = new GameWindow(new GameWindowSettings
            {
                IsMultiThreaded = true
            }, NativeWindowSettings.Default);

            gameWindow.RenderFrame += eventArgs =>
            {
                GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
                Console.WriteLine(GL.GetError());
                gameWindow.SwapBuffers();
            };
            gameWindow.Run();
        }
```

### Expected behavior

Screen to render blue and GL.GetError to return NoError

### Actual behavior

Screen does not render blue and GL.GetError returns InvalidOperation

### Related information 

* Operating system = Windows 10
* SDL or Native backend
* What version of OpenTK (Installer, NuGet, Source Code) = 4.0.0-pre9.1
* What runtime (.NET Framework, CoreCLR, Mono) = NetCore 3.1
* Workarounds (if any) = If you set isMultiThreaded to false everything works. You can also move the GL calls to `gameWindow.UpdateFrame` but that seems to defeat the purpose of a separate render thread.

**Comment by jvbsl** [comment]
Should be the same as that one(or at least the same fix)
https://github.com/opentk/opentk/issues/1052
I already know the problem and the fix for it. But I wanted to get it out with a sensible context option(Which I'm still not really sure how to do nicely with the limited C# features :D

Thanks anyway for reporting, anything else related to that, please write on the above mentioned issue.
