### ISSUE TITLE
Embedding OpenTK 4.0.0

### ISSUE THREAD

**Issue by shults-s** [opentk/opentk#1155]
### Description
If I get it right, in OpenTK 4.0.0 the entirety of OpenTK's platform-specific OpenGL context management code has been stripped out in favor of a dependency on GLFW.

It's a big problem for those who looking to embed hardware accelerated rendering in an existing UI toolkit like [Eto.Forms](https://github.com/picoe/Eto) or Windows.Forms, as GLFW doesn't currently allow creating a GL context from an existing native window handle ([for 7 years now it has not allowed](https://github.com/opentk/opentk/issues/1097#issuecomment-665830115)).

What can be done in this situation?
Does this mean that OpenTK is no longer worth considering for embedding hardware accelerated graphics in GUI applications?

**Comment by uzername** [comment]
It's a very specific subject in OpenTK. 

Right now OpenTK targets .NET Core, and neither WPF nor WinForms can be run in crossplatform manner.

**Comment by shults-s** [comment]
Well, thank you!

**Comment by NogginBops** [comment]
@shults-s I don't think closing this issue is the right thing to do.
We have not given up supporting these platforms. It is true that built in support is lacking for these frameworks, but it's possible to add support for them (even at the user level).

What needs to be done to load the opengl bindings is call `GL.LoadBindings` with an `IBindingsContext`, right now there is only one implementation of that that uses GLFW, but we are trying to figure out a good solution to some of these problems.
If the framework you use already provides a gl context implementing the `IBindingsContext` is pretty simple (only one function to implement which is basically delegating the proc loading to the existing context).

For other platforms like WPF some trickery is needed because there is no gl context there (wpf uses directx), atm there is an effort to create a WPFControl using the opengl/directx interop extensions [here](https://github.com/varon/GLWpfControl) (it's 3.0 but should be able to be updated for 4.0 without too much issue I don't think)

**Comment by shults-s** [comment]
@NogginBops
I understand that you not given up supporting. It's just that at the moment the project's priorities are slightly different. Close this issue when you see fit.

**Comment by NogginBops** [comment]
If you want more guidance and support with any topic related to OpenTK (like creating your own `IBindingsContext`) I recommend joining the discord server where you can get a lot of help from people who know OpenTK well.

**Comment by varon** [comment]
@shults-s - Please do have ago creating an `IBindingsContext` and initializing them manually.

This absolutely should work in your use case.

**Comment by shults-s** [comment]
@NogginBops @varon 
Thank you for your advices!

**Comment by varon** [comment]
@shults-s  - Currently working on embedding this in our WPF control.

See: https://github.com/varon/GLWpfControl/tree/netcore 

This was surprisingly easy to get working and includes dx_interop for incredible performance.

**Comment by varon** [comment]
@shults-s  - This turned out to be amazingly easy to do.

Just create a hidden GLFW window to create the context etc and then everything automagically works.

**Comment by shults-s** [comment]
@varon
Thank you very much!
You did a good job, I suppose that the issue is now can be closed.
