### ISSUE TITLE
Mousewheel.ScrollDelta returns wrong values with fixed window update frequency

### ISSUE THREAD

**Issue by RNG42** [opentk/opentk#1204]
### Description

Mousewheel.ScrollDelta returns wrong values with fixed window update frequency, but works as intended if UpdateFrequency = 0.

### Repro steps

1. GameWindow settings: 
    VSync = VSyncMode.On;
    UpdateFrequency = 60;

2. Get MouseState.ScrollDelta.Y within OnUpdateFrame

### Expected behavior

MouseState.ScrollDelta should return the amount that the mouse wheel moved since the last frame.

### Actual behavior

Mousewheel.ScrollDelta returns zero 95% of the time. The Mousewheel input seems to get lost between frames. 
This also includes the Offset variable from MouseWheelEventArgs in the OnMouseWheel event. 

### Related information 

Win10
OpenTK v4.2.0
.Net 5.0

**Comment by NogginBops** [comment]
Turns out this is an issue related with the multi-threading mode provided by `GameWindow`.
If the framerate is limited on either `OnRenderFrame` or `OnUpdateFrame` that function is just skipped when going through the update loop. Which means that input is still being processed as soon as it comes in.
This means that while we are waiting for the next update the event processing is rapid-fire checking all input (including scroll) and calculating deltas that never make it to the update function.

We have talked about removing the multithreaded feature of `GameWindow` as it doesn't have much use (if you are doing multithreading you're going to want your own thread anyways). 
This fix could be added to #1205 if we want to.

**Comment by RNG42** [comment]
Thanks for clarifying. The multithreaded option was indeed activated for some reason. Disabling it decreased the fps by ~10% with Vsync off, but thats actually not a big deal in my case.

**Comment by NogginBops** [comment]
Not sure what you mean with multithreading was activated? 
It should default to single threaded and setting `UpdateFrequency` and `RenderFrequency` to anything other than 0 should trigger this issue in the related function.

If you could clarify what you did to solve the issue that would be great.

As this issue isn't fixed yet I would like this issue to be open. :)

**Comment by RNG42** [comment]
Okay. So i had multithreading activated, because it gave a small performance boost. The gamewindow was set up with the GameWindowSettings as usual but with IsMultiThreaded = true. Your first reply discribed exactly what happened. Turning this setting to false solved the issue with returning wrong values of ScrollDelta, at least without using multithreading.

**Comment by NogginBops** [comment]
That's weird. Because when I reproed this issue I could get the issue without having the multithreaded option on.
There might be something I'm missing.

Would you be against sending your code to me so that I can test what is going on and find out why setting `Multithreading = false` fixes the problem? 
If not then no problem.

**Comment by RNG42** [comment]
I could setup a new project with the exact code i'm using right now to reproduce what is happening when IsMultiThreaded is set to true.

**Comment by NogginBops** [comment]
That would be fantastic. 
Thanks in advance!

**Comment by RNG42** [comment]
https://github.com/RNG42/IsMultiThreaded-Input-Issue

Here is the project. I also did some tests and documented the results in the readme.

**Comment by NogginBops** [comment]
It looks like the repository might be private (the link goes to a 404).

**Comment by RNG42** [comment]
oh, give me a second

**Comment by NogginBops** [comment]
Thanks a lot for the repo and the repro.
Will take a look at this and figure out what is actually causing the issue.

**Comment by varon** [comment]
Should be fixed by #1205 .

This is available in 4.3.0, which is up on Nuget in a moment!

**Comment by NogginBops** [comment]
That isn't a fix to this issue though.
There are still ways to trigger this issue.

This issue should still be open.

**Comment by NogginBops** [comment]
This should get fixed with #1436 .
