### ISSUE TITLE
OpenTK 4.0 Beginner's Guide

### ISSUE THREAD

**Issue by ghost** [opentk/opentk#1210]
### Description
Hi there. I am a complete noob in computer graphics and opengl. I am planning to learn OpenTK, however, existing documentations and example projects are based on OpenTK 3.x, not OpenTK 4.x (apologies if I am wrong), and OpenTK 4.x way of working, even window creation, is slightly different from OpenTK 3.x. It would kind if anyone give me any guideline, documentation or example projects for OpenTK 4.

**Comment by NogginBops** [comment]
You are correct that the current website and the [learn opentk repo](https://github.com/opentk/LearnOpenTK) are all using OpenTK 3. 

There is a [pull request](https://github.com/opentk/LearnOpenTK/pull/35) that updates the repo to OpenTK 4.
[Here](https://github.com/inputusernamehere/LearnOpenTK/tree/feature/4.0) is a more convenient link to that repo.
The parts that have changed between versions are windowing and input, so following the OpenTK 3 tutorial and referencing the OTK 4 repo is a good way to get both a written tutorial but also a up to date code reference. 
I also always recommend reading https://learnopengl.com while going through the tutorials (because they are based on that website) and because it's a good idea to get a c perspective on the API because that is the language that opengl was developed with in mind.

Someday we are going to get the tutorial up to date as well as OTK 4 documentation.

If you have more questions or just want to chat, feel free the join the discord. 
In the support channel you often get answers quickly.

**Comment by moon672** [comment]
> You are correct that the current website and the [learn opentk repo](https://github.com/opentk/LearnOpenTK) are all using OpenTK 3.
> 
> There is a [pull request](https://github.com/opentk/LearnOpenTK/pull/35) that updates the repo to OpenTK 4.
> [Here](https://github.com/inputusernamehere/LearnOpenTK/tree/feature/4.0) is a more convenient link to that repo.
> The parts that have changed between versions are windowing and input, so following the OpenTK 3 website tutorial and referencing the OTK 4 repo is a good way to get both a written tutorial but also a up to date code reference.
> I also always recommend reading https://learnopengl.com while going through the tutorials (because they are based on that website) and because it's a good idea to get a c perspective on the API because that is the language that opengl was developed with in mind.
> 
> Someday we are going to get the tutorial up to date as well as OTK 4 documentation.
> 
> If you have more questions or just want to chat, feel free the join the discord.
> In the support channel you often get answers quickly.

Thank you, brother, for the reply. I am looking forward into the updated documentations and would join the discord as well. Thank you.

**Comment by varon** [comment]
We are currently working on a new website which should offer updated tutorials as well.

I'm re-opening this for extra visibility until we get that done.

**Comment by NogginBops** [comment]
The https://github.com/opentk/LearnOpenTK repo has now gotten the opentk 4.0 PR merged. 
Now what remains is the website, which we will probably do when we get the new one.

**Comment by jameskolts** [comment]
Do we at least have API documentation for 4.0 ready to go? Trying to use this library, but a little frustration that existing documentation doesn't have correct details about namespaces, constructors, etc for things like GameWindow.

**Comment by NogginBops** [comment]
Unfortunately there is no web API reference for OpenTK 4. We are working on updating the website but progress is somewhat slow.
The code itself though is documented in source so it's definitely possible to generate documentation.

If you have any specific questions or just general advice on how to use OpenTK I recommend the discord (link in project readme). It's a great place to ask questions are advice. But you can also ask here on github if you want.

**Comment by devbatuhan** [comment]
API reference is empty

**Comment by NogginBops** [comment]
Yes, this is a know issue. We are working on updating the website, but we haven't spent the time to do it yet.
In the meantime you should get pretty far with looking at the samples and or looking at the relevant source code, specifically
https://github.com/opentk/opentk/blob/master/src/OpenTK.Windowing.Desktop/NativeWindow.cs
and

**Comment by NogginBops** [comment]
The website has been updated to contain tabs where you can switch between OpenTK 3 and OpenTK 4. With this I'm closing this issue.

**Comment by BuslikDrev** [comment]
Has anyone run OpenTK 4-5 on NET.Framework?

**Comment by NogginBops** [comment]
OpenTK 4 and 5 do not support .net framework. You can either upgrade to newer .net or you can stick with OpenTK 3 which does work on .net framework
