### ISSUE TITLE
GameWindow OnMaximized handler doesn't match window ClientSize

### ISSUE THREAD

**Issue by wo80** [opentk/opentk#1235]
### Description

If the GameWindow's `OnMaximized` handler is used, the `MaximizedEventArgs` property `IsMaximized` doesn't match the windows `ClientSize` property:
 * if `e.IsMaximized == true`, the non-maximized size is reported
 * if `e.IsMaximized == false`, the maximized size is reported

### Repro steps
1 . GL window code:
```c#
public class Window : GameWindow
{
    public Window()
        : base(GameWindowSettings.Default, NativeWindowSettings.Default)
    {
    }

    public Window(int width, int heigth, string title)
        : base(GameWindowSettings.Default, new NativeWindowSettings()
        {
            Size = new Vector2i(width, heigth),
            Title = title
        })
    {
    }

    protected override void OnLoad()
    {
        MakeCurrent();

        GL.ClearColor(1.0f, 1.0f, 1.0f, 1.0f);
    }

    protected override void OnMaximized(MaximizedEventArgs e)
    {
        System.Diagnostics.Debug.WriteLine($"e.IsMaximized: {e.IsMaximized}, ClientSize: {ClientSize}");

        base.OnMaximized(e);
    }
}
```
2 . GL window creation:
```c#
using (var window = new Window(800, 600, "OpenTK"))
{
    GL.LoadBindings(new GLFWBindingsContext());

    window.IsEventDriven = true;
    window.Run();
}
```
3. Maximize the window, then restore and look at the debug output.

### Expected behavior
The debug output should read:
```
e.IsMaximized: True, ClientSize: (1920; 1017)
e.IsMaximized: False, ClientSize: (800; 600)
```

### Actual behavior
The debug out reads:
```
e.IsMaximized: True, ClientSize: (800; 600)
e.IsMaximized: False, ClientSize: (1920; 1017)
```

### Related information 

* Windows 10 x64
* Native backend
* OpenTK 4.4.0 nuget package
* net 5.0

**Comment by NogginBops** [comment]
I can reproduce this issue.
The issue is that GLFW calls the maximize callback before the resize callback, so we don't update the size of our window before the maximized callback is called.

Fortunately it seems like GLFW updates the client area internally before calling the maximize callback so the information is available, and we should probably include it in the maximized event.
Though it it's unclear whether this is true for x11 or not, so there might exist a cross-platform inconsistency there, will be something to test (and the wayland code seems even weirder, but is that code even used?).

A workaround for now this issue would be to call this in the maximize callback.
```cs
int width, height;
unsafe {
    GLFW.GetWindowSize(WindowPtr, out width, out height);
}
```

**Comment by NogginBops** [comment]
Doh! 
I forgot to add make a PR for this in the latest release.

**Comment by wo80** [comment]
No problem, the solution for me was to only overwrite the `OnResize` method. The `ResizeEventArgs` will hold the correct window size.
```c#
protected override void OnResize(ResizeEventArgs e)
{
    // NOTE: use event args size info (window ClientSize not updated at this point).
    renderer.OnResize(e.Width, e.Height);

    base.OnResize(e);
}
```

**Comment by frederikja163** [comment]
I will assume this has been fixed, if not feel free to reopen and add further to the conversation.

**Comment by wo80** [comment]
@frederikja163 Why would you assume that?

The issue is no longer relevant to me, as I provided a workaround, but I haven't seen a commit that actually fixes it and 5.0.0-pre.3 still shows the same behavior as described.

**Comment by wo80** [comment]
Here's an updated example (same output for both OpenTK 4.6.3 and 5.0.0-pre.3). If this cannot be fixed in code, I'd suggest to add some documentation to not rely on the windows `ClientSize` property in the `OnMaximized` handler and point to the `OnResize` handler instead.
```
// Maximizing window

OnMaximized handler
  e.IsMaximized: True
  before base.OnMaximized
     ClientSize: (800; 600)
     WindowState: Normal
  after base.OnMaximized
     ClientSize: (800; 600)
     WindowState: Maximized
OnResize handler
  e.Size: (1920; 1017)
  before base.OnResize
     ClientSize: (800; 600)
     WindowState: Maximized
  after base.OnResize
     ClientSize: (1920; 1017)
     WindowState: Maximized

// Restoring window

OnMaximized handler
  e.IsMaximized: False
  before base.OnMaximized
     ClientSize: (1920; 1017)
     WindowState: Maximized
  after base.OnMaximized
     ClientSize: (1920; 1017)
     WindowState: Normal
OnResize handler
  e.Size: (800; 600)
  before base.OnResize
     ClientSize: (1920; 1017)
     WindowState: Normal
  after base.OnResize
     ClientSize: (800; 600)
     WindowState: Normal

```
Code:
```c#
protected override void OnResize(ResizeEventArgs e)
{
    Debug.WriteLine($"OnResize handler");
    Debug.WriteLine($"  e.Size: {e.Size}");
    Debug.WriteLine($"  before base.OnResize");
    Debug.WriteLine($"     ClientSize: {ClientSize}");
    Debug.WriteLine($"     WindowState: {WindowState}");

    base.OnResize(e);

    Debug.WriteLine($"  after base.OnResize");
    Debug.WriteLine($"     ClientSize: {ClientSize}");
    Debug.WriteLine($"     WindowState: {WindowState}");
}

protected override void OnMaximized(MaximizedEventArgs e)
{
    Debug.WriteLine($"OnMaximized handler");
    Debug.WriteLine($"  e.IsMaximized: {e.IsMaximized}");
    Debug.WriteLine($"  before base.OnMaximized");
    Debug.WriteLine($"     ClientSize: {ClientSize}");
    Debug.WriteLine($"     WindowState: {WindowState}");

    base.OnMaximized(e);

    Debug.WriteLine($"  after base.OnMaximized");
    Debug.WriteLine($"     ClientSize: {ClientSize}");
    Debug.WriteLine($"     WindowState: {WindowState}");
}
```

**Comment by NogginBops** [comment]
If no one has looked at this issue before I'm done with some of my outstanding PRs and other stuff I will take a look at this issue and make a fix.
From what I remember when looking at this issue is that it wasn't very hard to fix, it was basically just adding a function call or changing the order of some function calls.

**Comment by NogginBops** [comment]
It's actually unclear how to solve this issue. We could try to set the size parameters in the `OnMaximized` callback, but that will generate weird results for the subsequent `OnResize` callback. We could add size arguments to the `MaximizedEventArgs` struct, but idk if that is what we want.

Removing this from the 4.6.4 milestone so we can get 4.6.4 out.
I'm tagging @frederikja163 and @varon for ideas for a solution.

**Comment by PJB3005** [comment]
Maybe just have `ClientSize` be a property that just forwards to GLFW? Seems like the sanest approach to me.

**Comment by NogginBops** [comment]
This turns out to be "unsolvable" because the order of Resize or Maximized events is not defined by X11 and glfw decides to expose this. On windows and macos the order is consistent and the value returned by `glfwGetWindowSize` is updated before `OnResize` is called, but on X11 the window size is only updated *after* `OnResize` is called.
Which is a new bug that we didn't know about before, and I'll open an issue in glfw about it to see if we can fix this new issue there.

For this issue we've decided to just put a warning in the documentation for `OnMaximized` and `OnMinimized` and not guarantee an updated value for `ClientSize` in these callbacks.

**Comment by NogginBops** [comment]
I've now created an issue about `ClientSize` inside of `OnResize` in the glfw repo, linking it here for completion.
https://github.com/glfw/glfw/issues/2046
