### ISSUE TITLE
Texture parameter TEXTURE_MAX_ANISOTROPY is missing

### ISSUE THREAD

**Issue by Rabbid76** [opentk/opentk#1270]
Anisotropic filtering ([ARB_texture_filter_anisotropic](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_filter_anisotropic.txt)) is part of the OpenGL 4.6 standard. See [OpenGL 4.6 API Core Profile Specification - 8.10 Texture Parameters](https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf#page=260&zoom=100,168,616) 

However, the texture parameter TEXTURE_MAX_ANISOTROPY (0x84FE, 34046) is missing in `enum TextureParameterName` (`namespace OpenTK.Graphics.OpenGL4`). As well, the parameter MAX_TEXTURE_MAX_ANISOTROPY (0x84FF, 34047) is missing in `enum GetPName`.   

A workaround is to cast an integer value to the enumerator type:

```c#
float maxTextureMaxAnisotropy = GL.GetFloat((GetPName)0x84FF);
GL.TexParameter(target, (TextureParameterName)0x84FE, maxTextureMaxAnisotropy);
```

respectively

```c#
float maxTextureMaxAnisotropy = GL.GetFloat((GetPName)0x84FF);
GL.TextureParameter(textureObject, (TextureParameterName)0x84FE, maxTextureMaxAnisotropy);
```

**Comment by NogginBops** [comment]
This issue comes from the fact that be bindings generator uses an old `gl.xml` that doesn't have place these enums in their correct enum groups. Because of lacking knowledge of the current bindings and because the workaround isn't a lot of work I don't think it's worth fixing for OpenTK 4. With the new bindings generator being written for OpenTK 5 this will be fixed.

A better workaround that doesn't use magic numbers is to use the `All` enum as such:
```cs
float maxTextureMaxAnisotropy = GL.GetFloat((GetPName)All.MaxTextureMaxAnisotropy);
GL.TexParameter(target, (TextureParameterName)All.TextureMaxAnisotropy, maxTextureMaxAnisotropy);
```
