### ISSUE TITLE
(Follow up) A couple of questions

### ISSUE THREAD

**Issue by ghost** [opentk/opentk#1370]
(Follow up on [this](https://github.com/opentk/opentk/issues/1367#issuecomment-1015909669))
@NogginBops 

A couple of questions:

How do I build the open-source code for OpenTK in VS? I get thousands of errors, even after doing the [recommended steps](https://github.com/opentk/opentk/issues/1222#issuecomment-749684287).
I'll clarify repro steps if that is needed, just ask.

Is 5.0 discontinued? Last commit was 5 months ago, what's going on? Am I looking at the right [page](https://github.com/opentk/opentk/tree/opentk5.0)?

#

> To make your own overloads you need to create the appropriate function pointer and then call that function pointer in a static wrapper function. I can give you more information about this if you don't want to use this workaround

I prefer not to make my own wrapper, please provide me with more information, thanks. :)

**Comment by utkumaden** [comment]
5.0 is not discontinued, it is the current future branch. It's a bit stale because our maintainers and contributors are busy working on other things or with personal matters. In the 5.0 branch a new OpenGL binder, which means there are many issues with the generated methods, such as missing convenience overloads, incorrect enums.

The build system has a few quirks in that you must run build.cmd at least once before you can compile it through visual studio. Some projects in the solution will have errors, however those are not critical for building the graphics components. If you are having further trouble using a clean workspace can help. There are plans to make building the library way easier, however there is no ETA on this at the moment.

**Comment by wildniklin** [comment]
> The build system has a few quirks in that you must run build.cmd at least once before you can compile it through visual studio. Some projects in the solution will have errors, however those are not critical for building the graphics components.

I did these exact steps, as mentioned above in a link.
The errors still remained there, and I noticed there were missing enums within the OpenTK code...

15 passed, 6 failed in the build IIRC. Actually tried redoing these steps multiple times, reread the whole comment section multiple times, in case I was missing a step, I don't understand why it's not working...

#

* Windows 10 Pro, 64-bit
* Visual Studio 2022
* OpenTK Version: Release 4.6.7

**Comment by NogginBops** [comment]
Can you show what steps you are taking and the result of these steps. Ie. Does build.cmd succeed? Then can you show what errors you are getting both before and after running build.cmd?

**Comment by wildniklin** [comment]
Is there a way to keep the cmd open and make it not automatically close after it's complete?

**Comment by NogginBops** [comment]
Open cmd separately and then navigate to the OpenTK directory (using `cd`) and then run `.\build.cmd`.

**Comment by wildniklin** [comment]
Oh, I'm stupid, why didn't I think of that?

#

```cmd
D:\Projects\DotNet Program Projects\opentk-4.6.7>build.cmd

D:\Projects\DotNet Program Projects\opentk-4.6.7>REM Install .NET Core (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

'3.1.100' is not a supported value for -Quality option. Supported values are: daily, signed, validated, preview, ga.
If you think this is a bug, report it at https://github.com/dotnet/install-scripts/issues.
At line:244 char:19
+ ...   default { throw "'$Quality' is not a supported value for -Quality o ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ('3.1.100' is no...scripts/issues.:String) [], RuntimeException
    + FullyQualifiedErrorId : '3.1.100' is not a supported value for -Quality option. Supported values are: daily, sig
   ned, validated, preview, ga. If you think this is a bug, report it at https://github.com/dotnet/install-scripts/is
  sues.


D:\Projects\DotNet Program Projects\opentk-4.6.7>SET PATH=C:\Users\sande\AppData\Local\Microsoft\dotnet;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;c:\ffmpeg\bin;C:\Users\sande\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sande\AppData\Local\Microsoft\WindowsApps;C:\Users\sande\AppData\Local\atom\bin;C:\Users\sande\.dotnet\tools;C:\Users\sande\AppData\Roaming\npm

D:\Projects\DotNet Program Projects\opentk-4.6.7>.paket\paket.bootstrapper.exe
Checking Paket version (downloading latest stable)...
Hash file of version 6.2.1 found in cache.
Copying version 6.2.1 from cache.
Done in 0.92 second(s).

D:\Projects\DotNet Program Projects\opentk-4.6.7>dotnet tool restore
File D:\Projects\DotNet Program Projects\opentk-4.6.7\.config\dotnet-tools.json came from another computer and might be blocked to help protect this computer. For more information, including how to unblock, see https://aka.ms/motw

D:\Projects\DotNet Program Projects\opentk-4.6.7>dotnet fake run build.fsx
File D:\Projects\DotNet Program Projects\opentk-4.6.7\.config\dotnet-tools.json came from another computer and might be blocked to help protect this computer. For more information, including how to unblock, see https://aka.ms/motw

D:\Projects\DotNet Program Projects\opentk-4.6.7>
```

![image](https://user-images.githubusercontent.com/20182052/150207820-9400ec86-4cb0-4b4c-abfd-b71c9328ee64.png)

**Comment by NogginBops** [comment]
Ok so there are two things going on.
First is that our install script suddenly stopped working because of the `-Quality` option stopped working, but this should should not affect the actual build.

Second is the real issue, and as it's saying you need to unblock the file that it's saying is blocked. There is even a link to how to do that given in the message.

If it continues to not work after that then you can just give us those error messages and we'll try help you with those.

**Comment by wildniklin** [comment]
That removed most errors, just need to unload the unused programs now.
What programs are not needed? Is Generator related stuff not needed? What about OpenAL.Extensions?
Errors come from these places.

**Comment by NogginBops** [comment]
`OpenAL.Extensions` is unused.

**Comment by wildniklin** [comment]
Now I see why the built code isn't on github, it's absolutely  m a s s i v e.

> OpenAL.Extensions is unused.

What about the generator?

> (From the first post) I prefer not to make my own wrapper, please provide me with more information, thanks. :)

Everything throws BindingsNotRewrittenException?

**Comment by NogginBops** [comment]
The generator is used to rewrite the implementations of the functions in the GL class. This was needed in earlier versions of .net so that we could use the IL instruction `calli` to call function pointers directly.

Basically, there is no source version of the GL class in OpenTK 4 (or 3), you can only get a rewritten `OpenTK.Graphics.dll` that works. And that is what the rewriter does. 
This is something we have been able to simplify in OpenTK 5 as we now have function pointers as of .net 5.

If you can remove the generators or not is totally dependent on if you are going to have to rebuild OpenTK or not. The generator that has F# code in it is totally unused and can be removed (which is something we should do, but it just hasn't happened yet).

OpenAL generator is not needed, it's just a thing that helped me generate some of the source for the OpenAL bindings, but it's a completely manual process. None of it happens in a build step.

**Comment by wildniklin** [comment]
Thanks! :>

> Basically, there is no source version of the GL class in OpenTK 4 (or 3), you can only get a rewritten `OpenTK.Graphics.dll` that works. And that is what the rewriter does.

So I can't add the missing overload, e.g. my previous issue, to the GL4.cs file? Can I only use Helper.cs to add methods?
Do I need to make an XML documentation file and do all of that black magic, and then rebuild with .cmd, or something like that?

#

Yet another problem has occured... I can't set severity of this error for some reason:

![image](https://user-images.githubusercontent.com/20182052/150232598-fd934631-3aa9-412b-b2cc-13e9a1fee338.png)

I've selected "set severity" >"none", but nothing happens, and these errors stay there.

#

> This is something we have been able to simplify in OpenTK 5 as we now have function pointers as of .net 5.

Is there any downside to using 5.x instead of 4.x? It looks like last commit was 5 months ago, assuming that there are probably bugs there in 5.x that doesn't exist in OpenTK 4 anymore.

**Comment by NogginBops** [comment]
I'm not completely sure how to add a new overload to be completely honest. 
I've been looking at the code for half an hour now and I'm no closer to understanding where you would need to change stuff to get it work.

My guess is that the `GL.ProgramUniform[1,2,3,4](uint program, int location, int count, uint* value)` overload is being changed into `GL.ProgramUniform[1,2,3,4](int program, int location, int count, int* value)` and then discarded because there already is such an overload, but I have no way to prove this theory.

There might be a possibility that adding the relevant overload to `overloads.xml` might do the correct thing, but I really don't know. Might be worth a shot?
https://github.com/opentk/opentk/blob/master/src/Generator.Bind/Specifications/GL2/overrides.xml

**Comment by wildniklin** [comment]
> There might be a possibility that adding the relevant overload to `overloads.xml` might do the correct thing, but I really don't know. Might be worth a shot?
> https://github.com/opentk/opentk/blob/master/src/Generator.Bind/Specifications/GL2/overrides.xml

I'll give it a try tomorrow, I've forked the repo for now.
##### Is it illegal to comment without questions? oops.

**Comment by NogginBops** [comment]
> > There might be a possibility that adding the relevant overload to `overloads.xml` might do the correct thing, but I really don't know. Might be worth a shot?
> > https://github.com/opentk/opentk/blob/master/src/Generator.Bind/Specifications/GL2/overrides.xml
> 
> I'll give it a try tomorrow, I've forked the repo for now.

Let me know how it goes 🙂

**Comment by wildniklin** [comment]
> > There might be a possibility that adding the relevant overload to `overloads.xml` might do the correct thing, but I really don't know. Might be worth a shot?
> > https://github.com/opentk/opentk/blob/master/src/Generator.Bind/Specifications/GL2/overrides.xml
> 
> I'll give it a try tomorrow, I've forked the repo for now.

Of course. Happy to help with anything honestly. :)

**Comment by wildniklin** [comment]
> Yet another problem has occured... I can't set severity of this error for some reason:
> 
> ![image](https://user-images.githubusercontent.com/20182052/150232598-fd934631-3aa9-412b-b2cc-13e9a1fee338.png)
> 
> I've selected "set severity" >"none", but nothing happens, and these errors stay there.

https://github.com/opentk/opentk/issues/1370#issuecomment-1016955630

It's still stuck at this error... I can't get rid of it... 
I've tried doing this, many times, and restarted VS multiple times...

![image](https://user-images.githubusercontent.com/20182052/150242528-462ce1e4-62cc-4374-a9df-6d48f5e2f466.png)

**Comment by NogginBops** [comment]
In our source the opening brace is on its own line. This should be something you've edited yourself. The original code will compile fine.

It's defined as an error in one of the stylecop rule files, but I don't know which one. You will have to find that file and edit it manually.

**Comment by wildniklin** [comment]
> The original code will compile fine.

Yes, that did compile perfectly. :)

> It's defined as an error in one of the stylecop rule files, but I don't know which one. You will have to find that file and edit it manually.

I tried editing them, but they suddenly stopped working, so I deleted them, now it works. If you want to take a look, you can look at my fork of OpenTK called WildTK. It doesn't build fully at the moment, I'm making some changes atm, keep that in mind.

I will make pull requests with an **unmodified** forked version of OpenTK, soon.
When I get to fix the missing overload, or something else when I find any issues.

**Comment by wildniklin** [comment]
(I'm still trying to figure out how this build.cmd works, how F# works, and how the F# generator project itself works as well, so please hold on, if you don't mind. I would appreciate it if you could point out some things in the Generator and how it works.)

**Comment by wildniklin** [comment]
I'm still nowhere closer to understanding how this building system works...

**Comment by NogginBops** [comment]
The thing with the opentk binder and building process is that the current maintainers have limited knowledge of how it works.
If you could detail what you want to accomplish rather than having me try to explain a system I barely know how it works.

**Comment by wildniklin** [comment]
Is there anyone that has decent experience with it?
What I want to accomplish, is, I moved some folders around and stuff, I'm wondering how I relocate the build output files to the new folder locations? Where are the output directories coded in the system?

**Comment by NogginBops** [comment]
Unfortunately there is no one that is active that knows much about the build system. Me and @varon I think would know most about it.

The output should just be the normal build output files as far as I know. Can you give some more details and maybe pictures of what you've done and what you want to do?

**Comment by wildniklin** [comment]
(ghost is me, I just recreated my account.)

Apologies for the late reply, I didn't get any notifications for some reason.

> The output should just be the normal build output files as far as I know. Can you give some more details and maybe pictures of what you've done and what you want to do?

One of these things is renaming OpenAL to Audio (filenames, namespaces, etc.), since it makes more sense, while the other folders are named Graphics, not OpenGL, and Compute, not OpenCL, etc. I think it would tidy things up a bit.



Another thing, is there a simpler approach to reference assemblies other than selecting all of the assembly files? Like nuget, where everything is packed into one package.

Changing versions of all projects to net6.0 (I don't know why I would want that version, but sure) seems to break things, before and after building with build.cmd. And the C# language version seems to cap at 7.3, any idea why?

![image](https://user-images.githubusercontent.com/98742501/152043875-08ba806a-3eb3-44b9-8970-8eb02a34adc0.png)
![image](https://user-images.githubusercontent.com/98742501/152043814-df412920-1a22-4c11-9f5c-1063dcb0406a.png)

Also just rewritten like half of the mathematics library, and it requires C# 8.0+

Last question, how do I implement the 5.x generator, if necessary?

> Can you give some more details and maybe pictures of what you've done?

Take a look at the public repo where I've done stuff to break things. whoops.

https://github.com/wildniklin/WildTK

**Comment by wildniklin** [comment]
###### Anyone here?

**Comment by NogginBops** [comment]
Closing this issue as it's old.
