### ISSUE TITLE
Requirement forOpenTK 3.x version

### ISSUE THREAD

**Issue by NitloadYoumu** [opentk/opentk#1375]
I want to get the source code of OpenTK 3.x used for .net framework. I want to learn from it and use it for my .net framework project.

**Comment by NogginBops** [comment]
Hi! I edited your issue to contain the original question so that other people wondering the same thing can find this issue.

As you probably figured out you can look at the `3.x` branch for the OpenTK 3 source code.
You can also go to a particular release and download the source zip or look at the commit associated with the commit.
Unfortunately we are missing tags for `3.2.0` and `3.2.1` so those are unfortunately not easily findable.
