### ISSUE TITLE
Change "ref" to "in" in Uniform methods

### ISSUE THREAD

**Issue by wildniklin** [opentk/opentk#1376]
Both `ref` and `in` parameter modifiers has basically the same behavior, but `in` is readonly within the scope, correct me if I'm wrong.

At this point of time, we currently have to add a ref keyword for each matrix passed in :

![image](https://user-images.githubusercontent.com/98742501/152227527-7ed4a578-9c31-461f-98ae-6c259a3ba6e8.png)

With `in` instead, you can **optionally** add the `in` keyword :

![image](https://user-images.githubusercontent.com/98742501/152228722-bf642046-0230-48ff-859b-26d79c154ccb.png) ![image](https://user-images.githubusercontent.com/98742501/152229501-9297eeb7-355f-4737-81e2-ecc515bec8d1.png)

This results in cleaner code.
#
* NuGet OpenTK 4.6.7
* Runtime: .NET 6.0

### Workarounds:

Currently I've just used the pure OpenGL pointer overload in my program object :

![image](https://user-images.githubusercontent.com/98742501/152229602-d8ee416e-88ab-4471-9a63-32f20ab0a04d.png)
![image](https://user-images.githubusercontent.com/98742501/152230011-c590148e-3a95-45ee-ad32-7becbaec887b.png)

Thanks :>

**Comment by NogginBops** [comment]
This is something that we've debated for some time when developing OpenTK 5.
We are currently leaning towards not doing this, the reason is the fact that the `in` keyword is implicit. This creates hard to find bugs where you thought you passed something by value but you infact sent it by reference.
The way we name our gl functions create this problem where value functions and pointer functions have the same name, this combined with generic overloads create confusion and hard to track down bugs.
This would all be fixed if the `in` keyword wasn't implicit, but unfortunately that's not how they designed the keyword.

**Comment by wildniklin** [comment]
> the `in` keyword is implicit. This creates hard to find bugs where you thought you passed something by value but you infact sent it by reference.

Would you mind clarifying a scenario where this could happen?


> We want to make it very clear when you pass something by pointer/reference vs passing by value as that reduced confusion and reduces bugs.

I respect that choice. It's a good idea to make it obvious that it's passed by reference. It's just my personal opinion that `in` is a bit tidier, but I won't force that on you all.

What about the vector/matrix struct math operations? they take `in` and not `ref`, I've read another issue about this, speculating whether ref or in should be used, or something like that, so why not use ref everywhere if you want it to be clear that it's passed by reference? At this point of writing, I just realized that some functions can remain with `in` since it doesn't generate garbage, e.g. vector operations (add, sub, mul, div), where each component does not access a different component.

**Comment by NogginBops** [comment]
The math library was changed from `ref` to `in` which was something I personally was against.
Having references be explicit is more important in the GL bindings because reference vs value can mean calling two different functions e.g. `glUniform1f` vs `glUniformfv`.

A case where `in` causes issues is something like the following:
```cs
// Function definition
void BufferData<T>(BufferTarget target, in T data, BufferUsage usage) where T : unmanaged, notnull;

// Usage
float[] vertices = { ... }
// Compile error: You can't send a reference to an array as a "notnull" type.
GL.BufferData(BufferTarget.ArrayBuffer, vertices, BufferUsage.StaticDraw);
```

For the brief time we had in parameters in OpenTK 5 we got multiple people having compile errors for code they thought would work.

But the issues might become more convoluted and sinister, though I can't come up with an example right now.

**Comment by wildniklin** [comment]
> A case where `in` causes issues is something like the following:
> 
> ```csharp
> // Function definition
> void BufferData<T>(BufferTarget target, in T data, BufferUsage usage) where T : unmanaged, notnull;
> 
> // Usage
> float[] vertices = { ... }
> // Compile error: You can't send a reference to an array as a "notnull" type.
> GL.BufferData(BufferTarget.ArrayBuffer, vertices, BufferUsage.StaticDraw);
> ```

I don't understand? So vertices is an array containing a bunch of floats, then passing it as a reference (while array is already a pointer to a collection of floats on the heap) and then that pointer-pointer could be null? Wouldn't this also apply for `ref` as well?

**Comment by NogginBops** [comment]
In this instance the user was confused why they couldn't pass the array, if the function would use `ref` the issue would be much more apparent.
```cs
// Usage
float[] vertices = { ... }
// Compile error: Need to pass vertices with the ref keyword.
GL.BufferData(BufferTarget.ArrayBuffer, vertices, BufferUsage.StaticDraw);
```

Here it would be more apparent that `ref vertices` wouldn't be the correct solution as that would send a reference to the array instead of a reference to the data. Which could lead you to figure out that you need to send it as `ref vertices[0]` instead.

**Comment by NogginBops** [comment]
Closing this as we will not be changing to `in`.

**Comment by wildniklin** [comment]
I'm sorry for wasting your time.

**Comment by NogginBops** [comment]
No, no. You've not wasted my time.
This was a relevant issue, and it's good to have these decisions documented on GitHub, as many of our discussions take place in the discord a lot of "decisions" never get documented in the GitHub repo.
So this has all in all been a productive issue. 🙂

**Comment by wildniklin** [comment]
Alright then. Thanks though. :)
