### ISSUE TITLE
WindowState = Fullscreen then IsVisible = true is insanely slow

### ISSUE THREAD

**Issue by wildniklin** [opentk/opentk#1387]
I measured the time taken for these two operations like so;

![image](https://user-images.githubusercontent.com/98742501/153408101-70002a45-55fe-43fe-89e0-da92812f1595.png)

<details>
<summary>Raw</summary>

```csharp
Stopwatch sw = Stopwatch.StartNew();
window.WindowState = WindowState.Fullscreen;
sw.Stop();
Console.WriteLine(sw.Elapsed.TotalMilliseconds.ToString() + "ms taken for WindowState = " + window.WindowState.ToString());

sw = Stopwatch.StartNew();
window.IsVisible = true;
sw.Stop();
Console.WriteLine(sw.Elapsed.TotalMilliseconds.ToString() + "ms taken for IsVisible = " + window.IsVisible.ToString());
```

</details>

The default NativeWindow settings are:

![image](https://user-images.githubusercontent.com/98742501/153408486-130d5c6a-0951-4e73-8aa5-e248fc6c4557.png)

<details>
<summary>Raw</summary>

```csharp
NativeWindowSettings nws = NativeWindowSettings.Default;
nws.StartVisible = false;
nws.Profile = ContextProfile.Core;
nws.APIVersion = new Version(4, 6); // Minimum required version
nws.NumberOfSamples = 8;
```

</details>

Here are the results when I try with WindowState.Fullscreen:

```
0.0753ms taken for WindowState = Fullscreen
7324.5915ms taken for IsVisible = True
```

~7.3 seconds just to fullscreen a window...

And here are the results when I try with any value other than Fullscreen:

```
0.0044ms taken for WindowState = Maximized
9.8958ms taken for IsVisible = True
```

```
0.0515ms taken for WindowState = Minimized
15.786ms taken for IsVisible = True
```

```
0.0082ms taken for WindowState = Normal
6.2958ms taken for IsVisible = True
```

These are more reasonable times.

#

Version: NuGet 4.6.7
OS: Windows 10 Pro - x64-based
Latest NVIDIA drivers.

#

Edit: After profiling, it seems that the hot path is within the GLFW library, so it's likely that you won't be able to fix this.
But who is to say this might be the case? You should still try to look into this.

![image](https://user-images.githubusercontent.com/98742501/153412869-401f27bb-9791-40c9-9963-4d1f23241c2a.png)

**Comment by seanofw** [comment]
It varies a lot by the hardware, too.  Fullscreen often requires resetting a lot of device registers on the graphics card, and sometimes interaction with the screen itself.  I've seen computers where it's almost instant, and computers where it's several seconds.

Also, since the hot path is in `SetWindowMonitor()`, how many physical monitors are attached to this computer?  How many video cards, too (integrated GPUs on the motherboard included)?  Are there any kinds of weird external USB monitors on it?  All of that factors in to how long this could be taking.

**Comment by wildniklin** [comment]
> Perhaps with a debug build of GLFW we could see what exactly is going on, but to see if my suspicion has ground, could you tell me what size the window is when you do this?

Just the default size, no size is actually set in the code. (640, 360) by looking at the source code.

The monitor resolution is 1920x1080 on all three of them.

#

> Also, since the hot path is in SetWindowMonitor(), how many physical monitors are attached to this computer?

Three monitors.

> How many video cards, too (integrated GPUs on the motherboard included)?

One GPU, zero integrated GPUs, just one dedicated GPU.
If you're wondering what GPU, it's a Nvidia GTX 1060 with 6GB dedicated VRAM.

> Are there any kinds of weird external USB monitors on it?

Nothing weird, just regular video cables. (DP and DVI), and of course I plugged the video cables to the GPU, not to the mb. :)

**Comment by wildniklin** [comment]
It's something on GLFW's end, I started making a game engine in C++ just a few weeks ago.
We can always rely on borderless windowed fullscreen though.

**Comment by seanofw** [comment]
For my part, I haven't been able to reproduce this at all, despite trying.  Switching back and forth between windowed and fullscreen on my computer is milliseconds, not seconds (although it usually can take up to a second for the monitor to switch resolutions, but that's still way less than the 10-second range you were looking at).

Have you considered trying a debug build of GLFW to see where it's stalling?  Maybe there's a bug we need to report to them.

**Comment by wildniklin** [comment]
> Have you considered trying a debug build of GLFW to see where it's stalling?

How do I do that? Is there a file somewhere that I could use?

**Comment by seanofw** [comment]
No, you just clone the GLFW repository and compile a debug build of it, and then use that instead of the build we include.  That'll give you the ability to set breakpoints in it, see symbols, and all the usual debugging stuff, so you can find out where it's getting stuck.

**Comment by wildniklin** [comment]
![image](https://user-images.githubusercontent.com/98742501/156178290-75698de0-be5e-43b9-8ebb-722fb1b2f09b.png)

File location in GLFW repo shows in between the tree and the code btw
Oddly enough, I run this in x64 but the context of this is in Win32?
I have no idea what this code actually does, it would be nice to know, please let me know, if you do know what this does.

**Comment by seanofw** [comment]
So that's interesting.  You've found a bug in your video drivers.

The code in question iterates through the list of all known video modes for a given monitor.  It only runs once, and the results are cached.  It does so by asking the Windows for the available list of possible video modes, and then it asks Windows to _test_ each mode to see if switching to that video mode would actually work.

Then, after the full set of usable video modes is known, it sorts the result, and caches it.  Finally, it uses a simple search to switch to the video mode closest to the fullscreen video mode you requested.

The highlighted code is the code that _tests_ the video mode to see if it would work, and apparently it's pretty slow:  Your video driver does something bad internally that causes it to spend several _seconds_ trying to figure out whether a video mode will work or not.

The reason they added that test was because some video drivers are bad in a _different_ way, and return a list of video modes that includes modes that don't work at all, and that was causing weird crashes for some users or horrific slowdowns in other ways.  So after the video driver says, "I support these modes," GLFW makes sure to actually _test_ each mode to be certain it's actually supported.

The GLFW issue where they were working on this last, in 2015 --> https://github.com/glfw/glfw/issues/550

They didn't actually arrive at a *good* conclusion at the time, just an _acceptable_ one.  It appears your hardware is set up in such a way that it still triggers one of the bad corner cases they were fighting at the time.

Perhaps a more ideal solution (just spitballing here now) would be to "trust but verify" — instead of upfront testing every mode to make sure that only working modes are returned, return every mode the driver claims to support; but then just before trying to _use_ that mode if requested, they would test it, and if it doesn't work, they would mark it as invalid, and then retry the same algorithm.  That would still have negative behaviors (breaking changes), though, because GLFW would still be returning a list of video modes where not all of them work, and it wouldn't know which ones do or don't without actually trying them.

This is a hard one to fix, because the bug/issue is fundamentally in the video drivers themselves:  GLFW already has workaround code to deal with the video driver having bugs about which modes it supports, but it's that workaround code that you're waiting for on your computer, for whatever reason.

There's no easy answer here.

**Comment by seanofw** [comment]
This issue also seems to be related.  --> https://github.com/glfw/glfw/issues/1223

One guy at the end of the thread managed to fix it by "editing EDID extension blocks" to remove unsupported resolutions and old monitors from his computer.  I don't know what that means, to be honest ^_^;

Suffice it to say that either way, this is well outside the scope of OpenTK:  It's some kind of bad interaction between the video drivers, the OS, and GLFW, and I'm not fully inclined to say that of the three of those GLFW is what's actually at fault, either.

**Comment by wildniklin** [comment]
> So that's interesting. You've found a bug in your video drivers.

That's definitely interesting for sure
I've tried updating NVIDIA drivers, but no, that doesn't work, I tried that when I was using OpenTK, early up in the thread.

> One guy at the end of the thread managed to fix it by "editing EDID extension blocks" to remove unsupported resolutions and old monitors from his computer. I don't know what that means, to be honest ^_^;

Me neither...
I've searched a bit more and clearing cache of previously connected monitors in regedit might help?

`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Configuration`
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Connectivity`
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\ScaleFactors`

I see a lot of folders inside of these folders, and the keys seem legit for monitor information, e.g. HSync, PixelFormat, etc.
If each of these folders in the folders are the previously connected monitors, how did I even connect that many to my system?
There's like at least 12.

I'm a bit worried that this might break things, or even worse, causing the display outputs to stop working...

**Comment by wildniklin** [comment]
I tried disconnecting both my left monitor and my right monitor, and now it fullscreens fast, and then after reconnecting those two monitors again, it STILL fullscreens fast, what??!?!? I don't understand anything anymore...

**Comment by seanofw** [comment]
I think I'm going to officially go on the record as saying that my official answer to your problem is ¯\_(ツ)_/¯

But seriously, I guess you found the answer.  If it's slow, your monitors/drivers/Windows are weird and screwy:  Try deleting caches, reinstalling drivers, or unplugging stuff.  File for future reference.
