### ISSUE TITLE
GL.ShaderSource deviates from OpenGL spec

### ISSUE THREAD

**Issue by tilkinsc** [opentk/opentk#1409]
### Description
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glShaderSource.xhtml
According to `glShaderSource` the call is supposed to look as so
```
void glShaderSource(
 	GLuint shader,
  	GLsizei count,
  	const GLchar **string,
  	const GLint *length);
```

However, the OpenTK OpenGL4 source only exposes
```
GL.ShaderSource(int shader, string @string);
```

Most of the call to `ShaderSource` is fine as most parameters are able to be deduced by the second parameter. However, if you notice the first parameter is a `GLuint`. It's a `GLuint` for a good reason. This causes the end user to have to explicitly cast a `uint` to an int for following the OpenGL API.

Please note that `GL.CompileShader(int shader)` and `GL.CompileShader(uint shader)` both exist.

Would this be feasible to change? Absolutely even if internal operations have to be neglect supporting just int.

Would this change impact other users? Absolutely you should deprecate the function and implement the proper API call or support both. Some people who use a -1 as a signal will be most impacted and be force to write better code.

Does this change matter? Spit shine and polish is a perfect reason on it's own. C doesnt differentiate uint from int but there is absolutely no reason to let users be able to allocate negatives.

Perhaps this issue should be extended further passed just this function because it appears to be a reoccurring theme despite me having any evidence on the mind.

### Expected behavior
Please create a proper overload which handles uint for shaders.

### Actual behavior
End user has to succumb to using incorrect datatypes or manually casting.

### Related information 

* Operating system
windows
* SDL or Native backend (if using OpenTK 3.x)
latest native
* What version of OpenTK (Installer, NuGet, Source Code)
fresh nuget
* What runtime (.NET Framework, CoreCLR, Mono)
.NET Core 6.0
* Workarounds (if any)
explicit cast to (int)

**Comment by ohtrobinson** [comment]
I can't say this is a good idea to implement - to my knowledge most functions have an overload to take a `uint` anyway. And many people, myself included, just use regular `int`s so changing this and everything else to be `uint` only would be a massively breaking change.

So if you're saying that an overload that accepts a `uint` is missing and should be implemented, then it could be done, but if you're suggesting that it should be changed to only support `uint` then it's really not a good idea to change.

**Comment by tilkinsc** [comment]
It's all fun and games until...
```cs
int a = -1;
System.Console.WriteLine($"{a}"); // -1
uint b = (uint) a;
System.Console.WriteLine($"{b}");  // 4294967295
int c = (int) b;
System.Console.WriteLine($"{c}"); // -1
```

Then you are now debugging some undefined behavior as a result of something hardly detectable. It's totally justifiable to prevent this issue in the first place.

Besides this, it can be released in a major change such as 5.0.0, where breaking is 100% expected.

**Comment by NogginBops** [comment]
I'm not sure if there is a problem here or if it's just about a preference for `uint` over `int`?

> int a = -1;
System.Console.WriteLine($"{a}"); // -1
uint b = (uint) a;
System.Console.WriteLine($"{b}");  // 4294967295
int c = (int) b;
System.Console.WriteLine($"{c}"); // -1

Also I'm not sure how the code example here is anything undefined?

**Comment by tilkinsc** [comment]
The example isn't but the behavior exhibited is an example of an oversight a programmer could easily do and wonder why their geometry isn't rendering right when a load error occurs for example. Literally any OpenGL handle that gets passed as a number < 0 is going to be something > 0. In a worst case scenario this could create artifacts where something totally irrelevant is rendering probably a big black square.

**Comment by utkumaden** [comment]
If you ever treat that shader name as anything but a handle, and have more than 2^31 shader programs you have problems greater than the uint and int semantics.

**Comment by NogginBops** [comment]
As other people have pointed out, OpenGL names (handles) are opaque. They should not be treated as numerical values. All that matters is a bitwise equivalence between the values C# and the driver sees. And for that it doesn't matter whether it's an `int` or `uint`, the current functions passes the bitwise values without modification.

I could see an argument being made for following the gl spec more by using `uint`, but as `uint` is not CLS compliant (this doesn't really matter but still) and `int` is the more common C# data type, and the fact that it would be a breaking change doesn't make it something we want to do. Functions will use `int` for gl handles in OpenTK 4.

With OpenTK 5 we are introducing types handles which means that instead of working with `int`s directly you will have something like `ShaderHandle` instead.

**Comment by tilkinsc** [comment]
Honestly prefer mixture of int uint and random explicit casts through my code than masking handles with a name such as ShaderHandle. This whole library has achieve an uncanny status, why not add more.

**Comment by NogginBops** [comment]
I'm not sure why you are even using `uint` for anything. Just use ints everywhere and there is no problem.

No sure what you mean with uncanny status?

**Comment by utkumaden** [comment]
We are moving the object names to their dedicated enums, because after some request to Khronos they properly exposed object name groups to the specification file. For anything else the points you have brought up could have been important, but the only magic value you should be comparing with shader names is `0`, as this is the null object ID for all bind slots. What matters is that whether the bit sequence that makes up the object name is _not_ equal to zero. Not its proper value.

In the next release neither `int` or `uint` variants of these functions will exist. I personally think this is a [wontfix]. Not only that, touching the old generator in any way is playing with fire near a powder keg.

**Comment by NogginBops** [comment]
I don't think there is anything to fix here really, so I'm closing this issue.
Feel free to reopen it again if you want to continue the discussion @tilkinsc

**Comment by tilkinsc** [comment]
Not necessary to reopen. I decided to reinvent the wheel.
