### ISSUE TITLE
Copying a byte array into a texture?

### ISSUE THREAD

**Issue by antithing** [opentk/opentk#1449]
I am using OpenTK in C#/WPF. have some image data as a byte array that I want to display using the OpenTK / GL renderer.

My bytes are from code that was built for Unity Game Engine, and i am converting it to OpenTK / WPF.

I load the image to the byte array, and have this code:

```
        public int LoadTexture()
        {
            byte[] bytes = _gv.GetTextureBytes(1); //grabs the byte array

            width = _gv.Width; //gets width of image
            height = _gv.Height; //gets height of image

            int tex;
            GL.Hint(HintTarget.PerspectiveCorrectionHint, HintMode.Nicest);

            GL.GenTextures(1, out tex);
            GL.BindTexture(TextureTarget.Texture2D, tex);

          
            GL.TexImage2D(TextureTarget.Texture2D, 0, PixelInternalFormat.Rgba, width, height, 0,
                OpenTK.Graphics.OpenGL.PixelFormat.Bgra, PixelType.UnsignedByte, bytes.ToArray());
           

            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter, (int)TextureMinFilter.Linear);
            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter, (int)TextureMagFilter.Linear);
            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapS, (int)TextureWrapMode.Repeat);
            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapT, (int)TextureWrapMode.Repeat);

            return tex;
        }
```
However this crashes with (process 43564) exited with code -1073741819.

Where am i going wrong here?

How can i send a byte array into an OpenTK texture and display it?

**Comment by utkumaden** [comment]
Hello, and welcome. We usually prefer answering questions like this in our discord which you can find a link in the main repository page, and also here https://discord.gg/6HqD48s

-1073741819 is a segmentation fault/access violation. Either your width and height parameters are too large, or your bytes array is too small. Also you do not need to copy the your array by calling `.ToArray()`.

An access violation happens when the program tries to read memory that does not exist, or is null (at address 0). I think it will be hard to help you unless you can provide us more context about `_gv.GetTextureBytes()`

**Comment by antithing** [comment]
Thank you! I actually just found the answer, i was using teh wrong format. 

`  GL.CompressedTexImage2D(TextureTarget.Texture2D, 0, InternalFormat.CompressedRgbaS3tcDxt1Ext, width, height, 0, _FrameBytes, bytes.);`

has this working for me. Thank you!
