### ISSUE TITLE
Is it possible to have GameWindow to start with a black background instead of white?

### ISSUE THREAD

**Issue by aybe** [opentk/opentk#1514]
### Description

Long story short, when the window shows up, it is with a white background:

<img width="161" alt="XG4Lh" src="https://user-images.githubusercontent.com/1537591/191853943-1ef8834b-b5b1-457e-b85d-d5d7e846379f.png">

Even worse, if you dare starting the window with an aspect ratio such as 4/3, you are greeted with the following:

<img width="321" alt="Wipeout_m3PH9P7nNR" src="https://user-images.githubusercontent.com/1537591/191854310-989e2f43-8bc5-474f-b3c0-ddd303263266.png">

Setting GL.ClearColor and swapping in the constructor slightly improves this though it can still be seen.

Is there any way to change that color?

Thank you.

### Related information 

* Windows 10
* OpenTK 4.7.5
* .NET Core

**Comment by NogginBops** [comment]
Can you provide a repro for the 4:3 case?

**Comment by aybe** [comment]
Yes, here it is:

```
using OpenTK.Windowing.Desktop;

namespace ConsoleApp2;

internal static class Program
{
    private static void Main(string[] args)
    {
        using var window = new Game(
            new GameWindowSettings
            {
                UpdateFrequency = 60.0d,
                RenderFrequency = 60.0d
            },
            new NativeWindowSettings
            {
                AspectRatio = (4, 3)
            }
        );

        window.Run();
    }
}

internal class Game : GameWindow
{
    public Game(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
        : base(gameWindowSettings, nativeWindowSettings)
    {
    }
}
```

<img width="321" alt="ConsoleApp2_aagVKNHfGE" src="https://user-images.githubusercontent.com/1537591/192020657-32215b0d-9372-4b7c-9e74-43ba2470d518.png">

**Comment by NogginBops** [comment]
Ok so this is kind of a GLFW issue.
When GLFW creates a window it doesn't apply the aspect ratio constraint before creating the window, instead what happens is that the window is created (and the backbuffer is made white), then the aspect ratio is applied changing the size of the window (this resizes the backbuffer and makes the new content black). 
This causes a brief moment where the application has the wrong size, then is resized to the correct aspect with a black part, and then if you start drawing the black will disappear (given that you've called `glViewport`).

My recommendation would be set the window size to be a 4:3 resolution from the beginning so that GLFW doesn't have to resize it.

**Comment by NogginBops** [comment]
Closing this, but if you still feel like this is an issue feel free to reopen.

**Comment by aybe** [comment]
Sorry for the late answering...

That worked except that aspect ratio is not enforced anymore, but fortunately, the fix is really easy:

```
    protected override void OnLoad()
    {
        AspectRatio = (4, 3);
    }
```

Thank you!

**Comment by NogginBops** [comment]
Oh? So setting the size in `NativeWindowSettings` causes the aspect ratio limit to be ignored?

**Comment by aybe** [comment]
My bad, you're 200% right, matching the size to aspect in the constructor works perfectly:

```
        var nws = new NativeWindowSettings
        {
            Size = new Vector2i(640, 480), 
            AspectRatio = (4,3)
        };

        using var window = new MyGameWindow(GameWindowSettings.Default, nws);

        window.Run();
```
