### ISSUE TITLE
main

### ISSUE THREAD

**Issue by EWouters** [opentk/opentk#1535]
Can you please rename the master branch to main?

**Comment by NogginBops** [comment]
I've been thinking that we should probably make this change but I'm a bit hesitant to do it.
OpenTK has 13+ years of git history (and I haven't been here for most of it) and lots of people have worked on/with OpenTK. Changing the branch name has more consequences than people having to write `git pull upstream main` instead of `git pull upstream master`, there are lots of scripts related to OpenTK, many of which are either forgotten, no longer maintained, or the people who knew anything about them no longer maintain the project.
These scripts would break if I changed the branch name.

This could be things like build scripts, CI, etc.
These are things I'm not super knowledgeable about, and I'm not sure I would have the energy or knowledge to be able to detect and fix any of these breakages. OpenTK is already suffering from too little contributor time.

Is there a specific reason why you personally want to see this change?

**Comment by TheStolenBattenberg** [comment]
@EWouters I don't think anyone is going to facilitate you getting your nickers in a twist over the word 'master'.

**Comment by EWouters** [comment]
> Is there a specific reason why you personally want to see this change?

It does not feel right to me. Maybe we can ask @Github for help.

**Comment by utkumaden** [comment]
I find it odd that even though you are uncomfortable with the word, you did not hesitate writing it in all caps for the title.

Whilst I can see concerns over the hardware convention which indeed does reference slavery, in this instance the word is for the original copy of something. 

Changing the convention this late into the development of the library is going to break countless repositories and build scripts, as the maintainer explained.

That's just my two cents.

**Comment by EWouters** [comment]
I'm willing to fix the CI scripts in the repo.

**Comment by NogginBops** [comment]
> I'm willing to fix the CI scripts in the repo.

If you are able to take a look at what parts of the project would be affected by this change and compile that I could consider changing the branch name. 
I'm guessing CI would be affected, and potentially some of our other projects like the website and different controls we provide.

**Comment by EWouters** [comment]
I wonder what the origin of the word master is. In my mother tongue (Dutch) it (meester) can mean: "to be very knowledgeable about a subject", or "to be a teacher".

If we associate the word master with the meaning of original, or most important copy, I'm fine leaving it like this.

I just get triggered sometimes by other meanings of this word which are not intended here I suppose.

Focusing on removing words like "blacklist/whitelist" (allowlist/blocklist) currently has higher priority for me.

Thank you for the discussion, I'll close this as answered. 🙏
