### ISSUE TITLE
Include PAL2 in OpenTK 5 as an experimental api

### ISSUE THREAD

**Issue by NogginBops** [opentk/opentk#1553]
### Description

Pal 2 needs to get some real world usage to find potential design issues that are hard to fix in the future when the code is more mature. As such I've decided that the PAL 2 (platform abstraction layer) API is going to be part of the OpenTK 5 preview packages as an experimental API. This issue tracks that progress.

There are some open questions regarding this:
- Should all PAL 2 api be inside an `Experimental` namespace?
  This would look something like `OpenTK.Experimental.Core.Platform.IWindowComponent` or `OpenTK.Core.Experimental.Platform.IWindowComponent` instead of just `OpenTK.Core.Platform.IWindowComponent`.

**Comment by utkumaden** [comment]
My personal preference is `OpenTK.Experimental.<namespace>`. A top level namespace for all experimental features seems a bit easier to grasp instead of having a different experimental namespaces for each package. Another option is `OpenTK.<namespace>.Experimental` which might be easier to refactor later down the line.

**Comment by NogginBops** [comment]
PAL2 is part of the latest OpenTK 5 preview.
