### ISSUE TITLE
Callback made to garbage collected delegate

### ISSUE THREAD

**Issue by Khhs167** [opentk/opentk#1560]
### Description

When using `GLFW.SetCursorPosCallback`, the program will suddenly crash because the callback is collected by the GC

### Repro steps

1. Initialize a GLFW window with context etc
2. Create a cursor callback
3. Using GLFW.SetCursorPosCallback, set that callback
4. Move cursor

### Expected behavior

The callback is called

### Actual behavior

The program crashes with the following message:
```
Process terminated. A callback was made on a garbage collected delegate of type 'OpenTK.Windowing.GraphicsLibraryFramework!OpenTK.Windowing.GraphicsLibraryFramework.GLFWCallbacks+CursorPosCallback::Invoke'.
Repeat 2 times:
--------------------------------
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwPollEvents()
--------------------------------
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.PollEvents()
   at Soul.Engine.Engine.Loop()
   at Program.<Main>$(System.String[])

```

### Related information 

OS - Arch Linux x86_64
OpenTK Version - OpenTK 5.0.0-pre.8 from NuGet
Runtime - .NET 7

**Comment by utkumaden** [comment]
Hello there. This is an issue we can't do much about because of the way .NET works. When a delegate is decomposed into a native function pointer, the GC does not create a reference for it. You should keep a reference to the delegate like so:

```cs
CursorPosCallback callbackfunction = myFunction; // Or a lambda
GLFW.SetCursorPosCallback(wnd, callbackfunction);
```

This should prevent the crash from happening. Other more convoluted solutions exist, but this is by far the easiest, even if it means you need to declare a few more variables on the consumer code base.

**Comment by NogginBops** [comment]
This is "intended" behavior, as in we don't bother keeping the delegate alive. If you look at the source for NativeWindow you will see that we keep all delegate objects alive by keeping a reference to them.
I've been considering if the bindings should keep them alive but I've not decided on it yet

**Comment by NogginBops** [comment]
I've decided that because we would have to store the references per window (as that is how GLFW handles the callbacks) we will not be holding on to these references ourselves. This would complicate the bindings code and add inefficiencies that are avoided if users keep their own references.

Related PR: #1073
