### ISSUE TITLE
Mouse.Delta readings seem to be frame rate dependant 

### ISSUE THREAD

**Issue by KWEngine** [opentk/opentk#1590]
### Description

When using Mouse.Delta (i.e. to control camera rotation) there seem to be a lot of (0;0) readings when VSync is disabled, causing any linked movement to become slower and sluggish.

### Repro steps

Right now to reproduce the steps, you need to set RenderFrequency and UpdateFrequency to 0 and use the OnRenderFrame() for both updating game logic and render calls.
I implemented the section "the final touch" from here (https://gafferongames.com/post/fix_your_timestep/) in my engine.

1. Access Mouse.Delta from the OnRenderFrame() method with VSync disabled.

### Expected behavior

Mouse.Delta should provide the same readings regardless of fps count and regardless of from where it is called.

### Actual behavior

Mouse.Delta provides some small value readings and a lot of (0;0) readings inbetween when VSync is off and frame rate is uncapped.

### Related information 

* Windows 11
* OpenTK 4.7.7 (via NuGet)
* .NET6
* Workaround right now is to gather all readings and sum them up until a certain amount of time (like 1/240th of a second) has passed and then use this value instead of using Mouse.Delta directly. This results in smooth motion but the speed still differs from uncapped to a (for example) vsynced 60hz.

**Comment by NogginBops** [comment]
I think this is due to the Update and Render loop have separate timings in `4.7.7`, so in between frames when you are limiting your rendering to 60fps the update loop runs as many times as it can. And because input is updated in tandem with `OnUpdateFrame` you are missing a lot of the mouse input from `OnRenderFrame`.

This is kind of related to #1410 and #1430. 
Both of which are fixed with #1538 as we now run the update and render in tandem.

I'm going to release `4.8.0` assuming this is fixed, and we can reopen this issue if it turns out this issue isn't fixed.

**Comment by KWEngine** [comment]
Can confirm: problem has been fixed. Works identically with both vsync on and off. Great job, guys!
