### ISSUE TITLE
Cannot publish Hello World application using OpenTK 4.8.0 on Ubuntu 22.04-x64 (reopened, still problem). GLFW deps issue.

### ISSUE THREAD

**Issue by dockeratso** [opentk/opentk#1622]
## Description
It is not possible to publish an simple console application using .NET 7.0 with OpenTK 4..8.0 (the problem is still not solved).

## Repro steps
Setup a Ubuntu 22.04-x64 as a VM or as a wsl (Windows subsystem for Linux).
Install dotnet 7

Create a console application as follows:

dotnet new console --name TestOpenTK
cd TestOpenTK
dotnet add package OpenTK --version 4.8.0

Copy the following into the Program.cs file:

using OpenTK.Windowing.Desktop;
using (var window = new GameWindow(new GameWindowSettings(), new NativeWindowSettings()
{
StartVisible = false,
}))
{
}

Publish the application to produce binary executable:

dotnet publish -c Release -r ubuntu.22.04-x64

## Expected behavior
No errors. A correct built and published application

## Actual behavior
Error with conflict:

See log:

$ dotnet publish -c Release -r ubuntu.22.04-x64
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  Restored /home/scienta/TestOpenTK/TestOpenTK.csproj (in 240 ms).
/usr/lib/dotnet/sdk/7.0.109/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1142,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/home/scienta/TestOpenTK/TestOpenTK.csproj]
  TestOpenTK -> /home/scienta/TestOpenTK/bin/Release/net7.0/ubuntu.22.04-x64/TestOpenTK.dll
/usr/lib/dotnet/sdk/7.0.109/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /home/scienta/.nuget/packages/opentk.redist.glfw/3.3.8.38/runtimes/linux-x64/native/libglfw.so.3.3, /home/scienta/.nuget/packages/opentk.redist.glfw/3.3.8.38/runtimes/linux-x64/native/wayland/libglfw.so.3.3. [/home/scienta/TestOpenTK/TestOpenTK.csproj]

## Related information
If the OpenTK version is changed to 4.7.4, then the publish is ok. 

The problem is the dependent package: opentk.redist.glfw  with its native files.  Is it possible to solve the problem as in the previous version 4.7.4?

**Comment by Th3Dilli** [comment]
I am running into the same issue, I used the [1-CreatingAWindow](https://github.com/opentk/LearnOpenTK/tree/master/Chapter1/1-CreatingAWindow) example and update it to use version `4.8.0` and `net7.0`.


```
dotnet publish --self-contained -r linux-x64 -f net7.0 -c Release
MSBuild version 17.7.1+971bf70db for .NET
  Determining projects to restore...
  Restored /home/dilli/drive_linux/git_repos/anego/ConsoleApp1/ConsoleApp1/ConsoleApp1.csproj (in 194 ms).
  ConsoleApp1 -> /home/dilli/drive_linux/git_repos/anego/ConsoleApp1/ConsoleApp1/bin/Release/net7.0/linux-x64/LearnOpenTK.dll
/home/dilli/.dotnet/sdk/7.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /home/dilli/.nuget/packages/opentk.redist.glfw/3.3.8.38/runtimes/linux-x64/native/libglfw.so.3.3, /home/dilli/.nuget/packages/opentk.redist.glfw/3.3.8.38/runtimes/linux-x64/native/wayland/libglfw.so.3.3. [/home/dilli/drive_linux/git_repos/anego/ConsoleApp1/ConsoleApp1/ConsoleApp1.csproj]
```

I found this https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output

where you can temporarily make use of `<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>`

in the project file to ignore the error and then you end up with either of the two libraries (`runtimes/linux-x64/native/wayland/libglfw.so.3.3,` or `runtimes/linux-x64/native/libglfw.so.3.3`)

So the issue is that when you publish an app that uses OpentK 4.8.0 which has two libraries for glfw it. So on publish it will try to put all native runtimes into a single folder which fails and is exactly what the error also says.

A potential solution could be the rename the files to include a wayland pre or suffix and change the loading behavior in https://github.com/opentk/opentk/blob/master/src/OpenTK.Windowing.GraphicsLibraryFramework/GLFWNative.cs#L46 accordingly.
