### ISSUE TITLE
Minor API inconsistency: settings Size vs window Size / ClientSize

### ISSUE THREAD

**Issue by MV10** [opentk/opentk#1634]
As discussed in Discord:

`NativeWindowSettings.Size` is used to declare the initial window size. However, once the program is running, `NativeWindow.ClientSize` is the equivalent. If the program references `NativeWindow.Size` the full window rectangle (including borders and title bar) is returned.

While this is minor, it's easy to overlook `ClientSize` and assume `Size` reflects the initially-requested dimensions. In my case this led to a briefly confusing bug in which I was creating textures of the wrong dimensions.

![image](https://github.com/opentk/opentk/assets/794270/612887aa-f4c1-469a-97c5-70bf905a26b8)

**Comment by MV10** [comment]
@NogginBops since you tagged this 4.8.2, I'd be happy to PR this one. Any thoughts about how you'd like to address it? I'm babysitting release deployments tomorrow (Sunday), so if that proceeds drama-free, I'll be at my desk with nothing to do... might be able to knock this one out pretty quickly, I suspect.

Perhaps use `ClientSize` for initialization and maybe prevent `Size` from being set before the window exists? Or maybe `Size` should always be read-only? I haven't had a need to set the window-plus-decoration size, not sure if that works or is supposed to work, or even how you'd predict window-decoration size (maybe they're properties I haven't noticed?).

Or if you aren't sure yet, maybe I'll throw together some testing to see how they behave now, then propose something. I would need a little tester along those lines anyway if I work on this one.

**Comment by NogginBops** [comment]
We want to have both `ClientSize` as well as `Size` be gettable and settable. Operating systems (glfw) expose functions for getting the extents of a window, so that isn't really a problem.

What we likely want is to either change the name of `NativeWindowSettings.Size` to be `NativeWindowSettings.ClientSize` but the issue is we can't just remove `NativeWindowSettings.Size`, and keeping two different versions of `Size` and `ClientSize` in the settings can be confusing. A solution could be to put a `[Obsolete]` attribute on `NativeWindowSettings.Size`, and just make it work the same as `ClientSize`.

**Comment by MV10** [comment]
I see there is also `MinimumSize` and `MaximumSize` described as "Gets or sets the min/max size of the contents of the window."

For consistency, perhaps these should be obsoleted and replaced with ClientSize versions as well?
