### ISSUE TITLE
Unable to see the results from GL.Rect() with 4.8.0 but works with 4.0.0-pre9.1

### ISSUE THREAD

**Issue by mattdufeu** [opentk/opentk#1637]
### Description

I'm creating a Chip8 emulator. At the moment, I'm simply trying to render some pixels on the screen. I thought the easiest thing would be to use Orthographic projection to render the pixels with `GL.Rect`. 

I admit I don't know what I'm doing, so copied https://github.com/ronazulay/Chip8 which works. Unfortunately I can't get it to work and think I have traced the issue down to using 4.8.0 instead of 4.0.0-pre9.1

### Repro steps

1. Clone https://github.com/ronazulay/Chip8
2. Upgrade .NET target to `net6.0`
3. Confirm the emulator works using `4.0.0-pre9.1` (you need to drag and drop a ROM, say IBM logo from the rom folder into the window)
4. Upgrade `4.0.0-pre9.1` to `4.8.0`
5. Change the namespaces to OpenTK from OpenToolkit
6. Comment out anything to do with `Key` and `ProcessEvents` (I don't *think* those are needed)
7. Try again

### Expected behavior

I'm expecting the emulator to work, i.e. stuff rendered to the window.

### Actual behavior

Nothing rendered to the window.

I'm guessing I'm missing something and don't know what to look for. There are no errors in the console.

Any help, or better ways to render a byte array as pixels would be greatly appreciated!

**Comment by NogginBops** [comment]
I'm 90% certain that this is due to the default `NativeWindowSettings` changing.
Basically, to use deprecated OpenGL functions like `GL.Rect` you need to create a context with a compatibility profile.

So you need to set:
```cs
NativeWindowSettings settings = NativeWindowSettings.Default;

settings.Profile = ContextProfile.Compatibility;
// And remove the "ForwardCompatibility" flag.
settings.Flags = ContextFlags.Default;
```

**Comment by mattdufeu** [comment]
Fantastic, thank you, that's worked!

Out of interest, what's the proper way of doing this? I'm not bothered about it being deprecated for something like a Chip-8 emulator, but presuming I progress to something a little more modern I should figure out the right way.

**Comment by NogginBops** [comment]
To read about how modern OpenGL works I recommend reading https://opentk.net/learn/index.html which is a C# port of https://learnopengl.com/

Modern OpenGL can seem intimidating as the learning curve is steeper in the beginning, but it does pay off.
If you find yourself stuck on something don't hesitate to pop by our discord and ask away :)

**Comment by jvbsl** [comment]
It depends on what you want to do. And there are multiple solutions to a lot of problems, which sometimes work differently well on different hardware.
If you really want to draw pixel by pixel it could be that the best way would be to actually update a texture and only draw that texture(Dependent on the what you need to do could be done in a compute shader, using render to framebuffer or doing it on the CPU). If you want to draw bigger regions it could be helpful to draw rectangles using a VBO, either by updating the VBO with static rectangle positions(often pretty fast) or using a single VBO with different transformations(dependent on the rectangle count can become pretty slow, as the goal is to reduce opengl calls which need to sync with the gpu, which each drawcall needs to do). And perhaps even rendering back to a texture if you want to only update from a previous frame and not have each frame independent from the frame before.

As I don't know enough about CHIP-8 rendering process I can't really tell what the best approach would be. But the way it looks to me whatever approach you use is probably good enough, because todays hardware is so much faster, and the graphics don't look that complicated to me

**Comment by mattdufeu** [comment]
Thanks again, lots to learn. Like you say, for Chip8, this is more than quick enough.
