### ISSUE TITLE
MathF or Math? (Matrix4.cs)

### ISSUE THREAD

**Issue by Witchs-Cat** [opentk/opentk#1673]
https://github.com/opentk/opentk/blob/19f4e04ee807731138c40e420fb05e753261f4c9/src/OpenTK.Mathematics/Matrix/Matrix4.cs#L1120

Can you use MathF instead of Math?

**Comment by NogginBops** [comment]
Seems like a reasonable thing to do, no reason to have the comparison be done in double precision.

**Comment by MV10** [comment]
I looked at all uses of `Math`... there are two more places in `BezierCurve.cs` where `MathF` might make sense:

https://github.com/opentk/opentk/blob/19f4e04ee807731138c40e420fb05e753261f4c9/src/OpenTK.Mathematics/Geometry/BezierCurve.cs#L215

https://github.com/opentk/opentk/blob/19f4e04ee807731138c40e420fb05e753261f4c9/src/OpenTK.Mathematics/Geometry/BezierCurve.cs#L260

Unless the thinking is that double improves the calc quality -- both cases declare a `c` variable as double a few lines above the `Pow` calls that are cast back to float. But that might be because `Math.Pow` expects a double. If I remember right, Microsoft inherited `MathF` from Unity by way of Xamarin. so this code might pre-date all of that...?
