### ISSUE TITLE
Could you provide a dot dash line interface? eg glLineStipple()

### ISSUE THREAD

**Issue by llibetter** [opentk/opentk#1704]
### Description

I need this feature in version 3.3.3.thanks

**Comment by NogginBops** [comment]
`GL.LineStipple` function should be available in the `OpenTK.Graphics.OpenGL` namespace, be aware though that `glLineStipple` has been deprecated since OpenGL 3.1 so you might not be able to use it.
See this post for more details: https://stackoverflow.com/questions/6017176/gllinestipple-deprecated-in-opengl-3-1
This also contains example code for a modern equivalent.

**Comment by llibetter** [comment]
> `GL.LineStipple` function should be available in the `OpenTK.Graphics.OpenGL` namespace, be aware though that `glLineStipple` has been deprecated since OpenGL 3.1 so you might not be able to use it. See this post for more details: https://stackoverflow.com/questions/6017176/gllinestipple-deprecated-in-opengl-3-1 This also contains example code for a modern equivalent.

Thank you for your response and suggestion, I really appreciate it.
