### ISSUE TITLE
What should happen when two vectors pointing in exactly opposite directions are slerped

### ISSUE THREAD

**Issue by NogginBops** [opentk/opentk#1736]
### Description

Currently in the code from #1735 we do a lerp when the angle between the two vectors is close to 0 and π.
For zero this is correct as lerp is the limit when the angle goes to zero, but for π this is not true.

There is no two-sided limit when the angle approaches π so the question becomes one of practicality and expectation.
What is the expected result when trying to slerp two exactly opposite vectors? NaN? Lerp? Nothing?

Here is the wolframalpha of the limit: https://www.wolframalpha.com/input?i=sin%28%281-t%29%CF%89%29%2Fsin%28%CF%89%29a+%2B+sin%28t%CF%89%29%2Fsin%28%CF%89%29b+as+%CF%89+goes+to+%CF%80

**Comment by yetyman** [comment]
Mathematically it could be handled a few ways, but as a tool in a framework i would want the smooth continuous behaviour so that visual glitches don't occur when this situation is encountered naturally.

If i slerp 2 vectors that are nearly opposite parallel i would still expect a normal slerp and in the perfect case an assumption just needs to be made about the angle on which the slerp movement occurs. I would recommend simply aligning with an arbitrary angle.

**Comment by NogginBops** [comment]
This issue has some interesting discussion and links
https://github.com/godotengine/godot/issues/53928
