### ISSUE TITLE
When building version 4.7.4 there is an error 'No keyfile specified or keyfile missing'

### ISSUE THREAD

**Issue by HuubVanAmelsvoort** [opentk/opentk#1744]
With VisualStudio2022 going to developer command line and then build. Getting No keyfile specified or keyfile missing" on the end of the build. I understand that I have to put -k <keyfile>, but where?

* Operating system Windows 10
* OpenTK 4.7.4 source code.
* .NET version 6.0.200
*

**Comment by NogginBops** [comment]
This is not really an error, it's a diagnostic message telling you that the rewriter hasn't been given a keyfile to make a signed assembly. We have not been doing signed assemblies for quite a while and it's unclear if this feature of the rewriter even works as it should.

We could probably remove this diagnostic to reduce confusion, but it's still a good diagnostic to have in regards to signed builds.

**Comment by HuubVanAmelsvoort** [comment]
Oke thank you. So the reason that I get the 'throw new BindingsNotRewrittenException();' has nothing to do with that message.
I have to look further, what can be wrong that I get that message after building the OpenTK version 4.7.4.
In the end I want to see the Extensions. var ext = GL.GetString((StringName)GL_EXTENSIONS);

**Comment by NogginBops** [comment]
Yeah so I took a look at OpenTK 4.7.4 and that version is before I made changes to the build system to simplify it. To compile OpenTK properly when using 4.7.4 you can do run `build.cmd` which will run the rewriter and do everything that is needed. In 4.7.6 I made it so that the entire project can be built from inside Visual Studio.

**Comment by HuubVanAmelsvoort** [comment]
Thank you for the information. The real problem is, that I want to upgrade Quake2Sharp to OpenTK version 4.8.2, and that was not working anymore after the upgrade. The same problem with the pre release 5.0.0. So I start working with the latest version and go to look what's the problem there. It has something to do with the textures. So close this and then if necessary I open an new issue.

**Comment by NogginBops** [comment]
One of the things that could have changed between the versions is the default `NativeWindow` settings to default to a forward compatible core context which disables legacy functions and behavior. So if your code relies on some legacy stuff it might have broken between versions.

Otherwise I recommend skimming over the release notes of the different versions and see if any of the changed marked as "breaking" could effect your program.

Will close this issue, but feel free to reopen if you are not able to figure it out. And if you where able to figure it out, it would be nice to know what the solution was.
