### ISSUE TITLE
Detect memory capacity mismatches in debug builds.

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#204]
From the [forum](http://www.opentk.com/node/3862).

glGetActiveUniform takes an integer capacity paramerter and also a StringBuffer. Internally we allocate native memory equal to the size of the string buffer (by calling StringBuffer.Capacity), if the capacity of the string buffer does not match the integer capacity parameter passed in we get a mismatch of how much memory is actually availible and how much OpenGL thinks it can use.

Methods like this should either:
A) Not include the integer capacity parameter and only go by the StringBuffer.Capacity (this does mean you can't limit the amount written without reallocation)
B) Use the minimum value value of the capacity parameter and StringBuffer.Capacity to actually pass to OpenGL. This is arguably confusing behaviour.
C) Give an error when capacity parameter is greater than the StringBuffer.Capacity. Maybe only in debug builds to keep release builds fast.

**Comment by j1s1e1** [comment]
Additional options would include:
D) Resize the StringBuilder to match the requested capacity inside the called function.
E) Create and return a StringBuilder, and not require it as an out parameter.

Since StringBuilders auto resize in managed code, either of these options allow the function to handle this detail without extra code in every calling function.

**Comment by varon** [comment]
Relates to #517 probably.

**Comment by varon** [comment]
Closing in favour of #517
