### ISSUE TITLE
Vector3d.Normalize

### ISSUE THREAD

**Issue by edgar005** [opentk/opentk#205]
Hi
the Normalize method gives NaN in some cases because of division by zero. It should be changed to:

```
 public void Normalize()
        {
           double l = this.Length;
           if(l == 0.0)
               return;

            double scale = 1.0 / l;

            X *= scale;
            Y *= scale;
            Z *= scale;
        }
```

**Comment by Phyyl** [comment]
I totally agree, normalizing zero vectors should return 0. I use it for direction vectors, it would really be helpful to not have an exception to handle in these cases and I can't think of any case where an exception is better than a zero vector. it's easy to check for its length before normalizing to know if the vector is "invalid" for normalizing.

**Comment by Frassle** [comment]
> This is time consuming.

Well yes if you write it out long hand every time but that's easy enough to put in an extension function.

> I can't think of any case where an exception is better


We wouldn't throw an exception in this case and that behaviour isn't even up for debate to be added! The current behaviour is that the returned vector has x,y,z set to NaN, the proposal is that all three should be set to 0.

> Do you have a reason for having NaN for the normal? (beside the effort to change the code)

The reason that returning NaN is the current behaviour is that it is:
1) Less code than returning zero, no if check to see if ```length == 0```.
2) The same behaviour as dividing floats by 0.
3) Means that ```Vector.Normalise(v) == (v / v.Length)``` which is what normalise is mathematically defined as.
4) Is a clear error value for what is mathematically undefined.

The advantages to changing it to return 0 are that it's simpler for some cases. The disadvantages are:
1) It's more code (which is a performance issue)
2) No longer matches float behaviour
3) No longer matches it's long hand definition (```v / v.Length```) 
4) While zero can be used as an error value (because it's not of unit length so it must be an error value from a normalise function) it's not as obvious as NaN.

1 and 4 seem the most important to me. Performance is always important, and having a clear error value means if you've got your math wrong (and passing in a zero length vector to normalise is wrong) it's more likely to blow up with NaNs then 0. Blowing up here is a good thing cause it shows something is wrong and you can go and fix it.

**Comment by amulware** [comment]
I've run into accidental Zero-normalisation quite a bunch myself, and it makes for some really annoying bugs to track down (since the NaNs propagate through your game state in all sorts of weird ways sometimes).

However, I still think that it is better behaviour then returning 0, for exactly the arguments given above.

What I do these days is simply use an extension method:
```
public static Vector3 NormalisedSafe(this Vector3 v)
{
    var l = v.LengthSquared;
    if(l == 0)
        return Vector3.Zero;
    return v / (float)Math.Sqrt(l);
}
```

I got pretty used to using this method where it makes sense, and prefer having the choice of which behaviour I want.
And where I do want to catch the special case, I either check the LengthSquared or call a Vector3.IsNaN() extension method.

I can see an argument to be made for including these two extensions in OpenTK, but I really think the default behaviour of Normalized (and Normalize) should use NaN. Most importantly because I really don't want unneccessary branches in my low level math code.

**Comment by Frassle** [comment]
I'm happy to consider adding in a NormalizeOrDefault method which you could call as NormalizeOrDefault(Vector3.Zero, vector) to get the wanted behaviour (also means if you need a default unit vector you can pass that as the default instead).

Adding IsNaN and IsInfinity also sound useful.

**Comment by varon** [comment]
Amulware has a solution for this by extension method. Closing.
