### ISSUE TITLE
Gamepad thumbstick Y-axis wraps around

### ISSUE THREAD

**Issue by Cireon** [opentk/opentk#209]
When getting the GamePad state, the Y axis of the thumbsticks wraps around when moving in the positive direction. This happens for both thumbsticks. I attached an image of the value of `GamePad.GetState().Thumbsticks.Left.Y` outputted to the console while moving the left thumbstick down. The negative direction works fine, and the X-axis also seems to work without problems (varying from -1.000031 to 1).

![image](https://cloud.githubusercontent.com/assets/828553/5669806/137f49c6-977b-11e4-89cd-79ebf738c25c.png)

It appears internally shorts are used. Maybe this issue is related to the Y-axis being inverted as well, running into problems because we have one less number on the positive side.

The problem occurs with an (emulated) XBox 360 controller, but using a third party controller does not have these issues.

**Comment by Frassle** [comment]
Ah yup think I've found the bug in our [XInput code](https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Platform/Windows/XInputJoystick.cs#L62)!

We invert the axis we receive from the XInput driver so that min -> max, and max -> min.

So for example we get -32767 from the driver we return 32767, and vice versa. For positive values this works fine, we get 32767 and return -32767 that's all within the range of Int16.
But when the driver returns Int16.MinValue (-32768) we negate it (which the compiler promotes to an Int32 operation) to get 32768, and then cast back to Int16 which is now out of bounds and wraps back to -32768.

**Comment by Frassle** [comment]
I think the right fix is to replace `(short)(-value)` with `(short)Math.Min(short.MaxValue, -value)`.

That will map `min` to `max` while everything else stays the same. Does mean both `min` and `min + 1` both map to `max` but that's probably fine.

**Comment by Cireon** [comment]
The value indeed goes up to -1 to the other side. I was not aware that XBox 360 controller was still using the XInput driver, but it explains why the issue only appears for XBox 360 controllers.
