### ISSUE TITLE
OS X, GamePad.GetState Crash

### ISSUE THREAD

**Issue by cra0zy** [opentk/opentk#257]
https://github.com/mono/MonoGame/issues/3790

**Comment by Frassle** [comment]
NullReferenceException in OpenTK.Input.GamePad.GetState (Int32 index) under both cocoa and sdl2.

**Comment by Frassle** [comment]
Ok that's very suspicious as GetState is a simple call into driver.GetState so an NRE in that method must be due to driver being null. But then driver is created via a call to factory.CreateGamePadDriver which just returns a new MappedGamePadDriver() which,
A) Has a very simple ctor that I can't see how it could fail
B) Even if it did fail would cause an exception at that point, not later when it was used.

**Comment by varon** [comment]
Closing. Seems to be an edge-case report.
