### ISSUE TITLE
Possible bug found in GL.Ortho(double left, double right, double bottom, double top, double zNear, double zFar)

### ISSUE THREAD

**Issue by wcdeich4** [opentk/opentk#263]
Hi.  I was just trying out some tutorials & noticed that no matter what I did, textures came out upside down & at the bottom of the screen instead of the top.  I tried everything until I realized changing the line GL.Ortho(0, Width,  0, Height, -1, 1); to GL.Ortho(0, Width, Height, 0, -1, 1); solved the problem.

Then I searched the source code & I believe line 6228 of line GL.cs may be the cause because the bottom and top parameters are transposed.  There is a similar transposure in the Begin function on line 256 of GL1TextOutputProvider.cs

Can anyone advise me how to submit a fix????????

**Comment by Frassle** [comment]
Parameter order in the entry point matches the specification https://www.opengl.org/sdk/docs/man2/xhtml/glOrtho.xml. I'm not sure about the GL1TextOutputProvider code, but generally each app can decided whether up is positive or negative so it's possibly not wrong.

**Comment by wcdeich4** [comment]
Hmm.  After re-examining line 6228 of line GL.cs, the parameters were passed to the delegate in the same order (not transposed), so that's not the bug.  But changing the line GL.Ortho(0, Width, 0, Height, -1, 1); to GL.Ortho(0, Width, Height, 0, -1, 1); did solve the problem where GL.Ortho worked backwards from ordinary OpenGL, so I think this bug should be researched, not closed.

**Comment by Frassle** [comment]
The entry point matches the specification. Whether up is positive in the y axis or negative is application defined, OpenGL (and thus OpenTK) do not care if you say bottom=0 top=100 or top=0 bottom=100 (or even top=-100 bottom=100), it's just setting up a coordinate space. If flipping your bottom and top parameters gives you the right results you've probably got a call somewhere else that's also flipped the y parameters.

Also per chance your not loading BMP files for your textures? Because they're stored "upside down" and if I recall System.Drawing.Bitmap doesn't flip them when loading.

**Comment by wcdeich4** [comment]
Well, I'm loading a jpg to a System.Drawing.Bitmap --- but what has me concerned is that it didn't just come out upside down, but at the bottom of the screen --- and it was that way for both the sample code in the TexLib example and when I copied the code from one of my old OpenGL projects..... 

... well, thanks for answering the messages....
