### ISSUE TITLE
Steam messes up Joystick input?

### ISSUE THREAD

**Issue by OverworldTheme** [opentk/opentk#273]
I'm currently setting up a game of mine for release on Steam, and I use OpenTK for most things, including input. It runs fine from the raw .exe, but when I run the exact same executable from within the Steam client, the Y axis of the left thumb stick is inverted, and the hat switch/d-pad is all messed up. (Just running the .exe as a non-Steam shortcut in the client will cause this behavior.)

Originally I was still using the old GameWindow joystick code, but I've updated it to use JoystickState instead, with no improvement. GamepadState will even crash with a NotImplementedException when run from the Steam client. Since I can't run through the Steam client and Visual Studio environment at the same time, I'm having a lot of trouble figuring out what's going on.

The Y axis issue can be worked around by simply giving the user the option to invert it, but for a 2d game I really need usable d-pad input and there's no reliable work-around. Been doing Google searches for a few days and searching through Valve's documentation, but I can't find *anything* on this.

I'm assuming the client intercepts the input somehow before feeding it to the application. Asked about it on the private Steam devs' forum a day or two ago, but so far I haven't gotten any response.

**Comment by tomrijnbeek** [comment]
Steam automatically inserts the SDL2 framework. Your input drivers are probably replaced with the SDL2 drivers which work differently. You can force native drivers by embedding all your game code in a

    using (Toolkit.Init(new ToolkitOptions { Backend = PlatformBackend.PreferNative }))
    {
        // here be games
    }

Make sure the using is the first thing in your Main method, and everything should work as intended.

**Comment by OverworldTheme** [comment]
Yeah, that seems to do the trick. Is this documented anywhere and I'm just missing it?

Is there any way at present to make things work with the SDL2 drivers? I'm assuming they're more consistent across platforms, but the hat switch/d-pad is unusable as OpenTK seems to get it stuck in the "up" position once any direction has been pressed.

In any case, thank a lot.

**Comment by tomrijnbeek** [comment]
I have read it somewhere and I was only reminded of it when I saw it happening in my own game, but I have not been able to find it again. It is probably somewhere within the section about redistributable frameworks.

We also ran into similar issues with OpenTK, and it seemed to behave differently for different types of joysticks/controllers, and using the native drivers seemed to do the trick for us (especially since they have been updated in/since the latest version). I can't give you any data on how the consistency of controllers is across platforms since I haven't been able to test it myself due to the lack of drivers, but you can always consider adding the option to rebind controls in your game, or at the very least use gamepad mapping files similar to how MonoGame works, if you want a more solid support across multiple platforms.
