### ISSUE TITLE
Mouse moved to closest window border after GameWindow looses focus

### ISSUE THREAD

**Issue by cra0zy** [opentk/opentk#281]
Mouse gets moved to the closest border a moment after GameWindow looses focus.

Video of the bug: http://youtu.be/PlErjp19RpY

**Comment by cra0zy** [comment]
I am currently tracking down the bug, I found that commenting out: https://github.com/opentk/opentk/blob/develop/Source/OpenTK/NativeWindow.cs#L602 fixes it.

**Comment by Frassle** [comment]
This is just on Linux?

**Comment by cra0zy** [comment]
> This is just on Linux?

yes

**Comment by Frassle** [comment]
So I think this ties in with #265 a little bit. It looks like this is from us trying to generate relative cursor events for X11 when the cursor is not visible. We do this by resetting the actual cursor to the middle of the window and then calculating deltas each frame that we report to the user. So when we make the cursor visible again it should show up where we report it is, not in the middle of the window.

What your experiencing is us doing that because the cursor is being set visible because it's moved out of bounds, and despite it already being visible we run the compensation code anyway. I think this might be as simple as changing the CursorVisible to only show/hide the cursor if it isn't already shown/hidden. I'll push a PR and if you could lemme know how that works (I'm away for a week so I'll test it myself when I get back)

**Comment by GiantBlargg** [comment]
I'm still having this problem on OpenTK 2.0.0.
