### ISSUE TITLE
OpenTK Maintainer

### ISSUE THREAD

**Issue by varon** [opentk/opentk#339]
As we've seen on the notice,  unfortunately @frassel has left the Project.

I'd certainly like to ensure that OpenTK continues to be used, and I hope that others who use the library share the same sentiment.
To this end, I've opened up this issue to discuss how we can move forward with OpenTK, and look at regaining some momentum behind this incredibly useful library in the future.

In the short term, I think we need to answer the following questions:
- Is there a successor project with the same goals?
- Who can take over as maintainer?
- Can we recover the OpenTK website?

I'd really appreciate any input and discussion from the members here, and I've included a few mentions of recent contributors: @mrhelmut @endimilojkoski @dellis1972 @tomspilman @frassle @thefiddler  @WardBenjamin

**Comment by tomspilman** [comment]
I only speak from my limited point of view as someone seeing bug reports and PRs for OpenTK problems in MonoGame.  @cra0zy @dellis1972 @KonajuGames and @mrhelmut might have more specific things to say about it.

It seems like OpenTK has made some good improvements over the last 2 years... but I personally got fed up with it still having issues with windowing and input working correctly and consistently across Windows, Mac, and Linux.  Contributors were often writing platform specific work arounds to hack around issues that OpenTK should have solved for us.  It was hard enough keeping MonoGame in working order without a core dependency being faulty itself.

A few weeks ago I suggested we move away from OpenTK in MonoGame and currently efforts are underway to switch to our own simple SDL2 wrapper for windowing and input with separate wrappers for OpenGL and OpenAL.  SDL2 is just used by more games, is better maintained, and is more reliable for our rather simple needs.

I think there is value in OpenTK still if it can find a reliable maintainer and community to fix its issues and keep it current for desktop platform changes in the future.  However I don't foresee MonoGame coming back to OpenTK at this point.

**Comment by varon** [comment]
@tomspilman Are the OpenGL and OpenAL bindings available 'upstream' of MonoGame, so that they can be used without the enormous dependency of MonoGame itself?

I'd also like to bring @flibitijibibo into this discussion as he seems to have a fair amount of history and experience with the library, based on readings of some issues in https://github.com/flibitijibibo/SDL2-CS.

**Comment by tomspilman** [comment]
> Are the OpenGL and OpenAL bindings available 'upstream' of MonoGame, so that they can be used without the enormous dependency of MonoGame itself?

No... we're not trying to make yet another binding library.  The plan is just to create bindings that meet the needs of MonoGame.  This means we are not binding the full API for any of these libraries...  just what MonoGame specifically uses and nothing more.

**Comment by varon** [comment]
Thanks for the answers, @tomspilman, they're super helpful. How much effort is involved in maintaining your own bindings? How do you relate these to whichever math library you're using?

**Comment by cra0zy** [comment]
> Is there a successor project with the same goals?

Nope :\

> Who can take over as maintainer?

In order for a project to be alive you need both maintainer and developers, and the person who should take over should be a developer, someone who can add useful code, and not just maintain OpenTK.

> Can we recover the OpenTK website?

Nope :\

> How much effort is involved in maintaining your own bindings?

We are in process of writing them, this can't be answered yet.

> How do you relate these to whichever math library you're using?

We aren't using any math libraries, and I don't think we will be using any math libraries, we have all the math we need within MG source. (https://github.com/mono/MonoGame/tree/develop/MonoGame.Framework scroll down a bit, you will see everything, Point, Vectors, Matrix, etc.)

**Comment by dellis1972** [comment]
@varon I think its great you are trying to keep this project going :) 

As a MonoGame contributor/maintainer I have to say OpenTK has been one of the biggest problems for us which is why the project is moving away from it. Two years ago we decided to stick with OpenTK rather than jump ship to SDL2 in the hope that things would improve and it did but unfortunately not enough for us to stay with it :( 

Another problem is the API break between this project and the mono/opentk, which causes all sorts of issues for developers since the mono/opentk bindings are the ones shipped with Xamarin.iOS and Xamarin.Android. Perhaps the new effort should focus on bringing mono/opentk up to date? It is maintained by developers at Xamarin and being part of the "mono" eco-system I'm sure it will be about for a good few years to come.

I am currently working on the new GL bindings for MonoGame, and they are going to be very focused and limited to the stuff MonoGame uses nothing more. I can't say how much effort it is to maintain yet as I've only just started :)

**Comment by mrhelmut** [comment]
mono/opentk sounds like the most relevant follow up to the project, even though it's not on par with the latest opentk and I don't know how much Xamarin is willing to push it forward.

My personal opinion will be same as other MonoGame users, a simple windowing and input support is the only thing I need and I don't have interest in opentk behind that point.

**Comment by wcdeich4** [comment]
Who made / controls the opentk website?

**Comment by wcdeich4** [comment]
As someone who does not use MonoGame, but only wants to make my own little flight simulator, it seems like OpenTK actually has too many features sometimes.  All I really wanted was an OpenGL cross platform window system in C#

**Comment by Frassle** [comment]
> Who made / controls the opentk website?

@thefiddler. He also is the only one with admin rights to this github.

**Comment by wcdeich4** [comment]
I got a couple private messages from @thefiddler on opentk on January 14th 2016.  It seems like he checks messages once a month or so.

**Comment by wcdeich4** [comment]
@Frassle since you've been approving Pull Requests, could you give permission for anyone else to approve Pull Requests?

**Comment by Frassle** [comment]
@wcdeich4 No, I was never given anything other than push rights to the OpenTK repo so I couldn't do anything to it but approve pull requests. I've now left the OpenTK group so I don't have rights for that anymore either now.

**Comment by leezer3** [comment]
Question-
Is anyone accepting pulls anywhere at the minute?

I've increased the number of available joystick buttons (After a user reported a crash to me...), which is the sort of thing which probably ought to be passed back to anyone else who is working on this.

I'm also rather tempted to change the code so that it doesn't throw a breaking exception if the number of buttons on the joystick are greater than supported (Why not limit to the max?), which again is something that others would probably benefit from.

Where we go is another kettle of fish entirely.
Everything I've done is small fry, but I'm happy enough to fix small issues as I find them. I think that a repository accepting pulls, even when it's small fixes is a good idea.
Whether the Mono official repositiory is the right place for this is something I don't know about- It feels as though we ought to set a feature set in stone, and attempt to get this pushed back to Mono, whilst contuing development on an unstable branch someplace :)

**Comment by amulware** [comment]
Slightly off-topic, but just so anyone only reading this issue knows:

**We are discussing possible ways of ensuring the project stays alive over here right now:**
https://github.com/opentk/opentk/commit/2e51fe019771f4c70b15bb25b3a560f712a45fbf

While we want to wait for @thefiddler to show up and hopefully give a few more people admin access so we can get this repo going again, we are considering creating a new community driven organisation, that will have multiple admins, and whatever other redundancies we think is necessary.

We are also considering creating a new forum, since the official one is all but overrun by spam bots.

I think that people like you, @leezer3 who can contribute the occasional fix/improvement, and maybe help review pull requests will be vital to keep things going - especially if 'the big shots' are unavailable.

**Comment by wcdeich4** [comment]
We made contact w/ @thefiddler, is anyone else besides me willing to be a Maintainer?

**Comment by WardBenjamin** [comment]
@wcdeich4 I might possibly be interested, but it would be hard due to the fact that I have my own framework now to maintain, which has many of the features of OpenTK already and is still improving a ton. I'll definitely have code to contribute every once and a while as I grow my framework that I can contribute back here, but I don't think I'm fit for a full management position. I would like this project to go on if possible, since it's a fantastic way to get into OpenGL using C#, but the code, documentation, and especially the website need some cleanup and community involvement that I do not think I would be fit to lead.

**Comment by wcdeich4** [comment]
@WardBenjamin - well, we'll always welcome high quality code contributions like yours

**Comment by WardBenjamin** [comment]
@wcdeich4 Good!

**Comment by amulware** [comment]
To clarify my stance: I am willing to be an admin/have push rights here, to make sure that we always have at least someone available to merge pull requests, and similar. For whatever it's worth, check the contributions graph on my profile and note how many of my repos rely on OpenTK as indicators that I will be around.

Please do not misunderstand: While I am willing to look into actually writing code for OpenTK, or reviewing pull requests, I do not know if I have the time it takes to get into it (not even sure how much that would be).

Still, I'd like to do what I can to enable others to work on OpenTK more easily.

**Comment by ilexp** [comment]
> To clarify my stance: I am willing to be an admin/have push rights here, to make sure that we always have at least someone available to merge pull requests, and similar.

This is a solid start. If we manage to assemble an admin team of 3-4 people with this degree of participation, I think we're on a good path. Contributors come and go, but as long as we have an organization that is giving direction, reviewing and merging PRs, I'd consider this a much needed success.

**Comment by amulware** [comment]
Small update:

**Comment by amulware** [comment]
Small update: @wcdeich4, @andykorth, @cra0zy, @BenjaminNitschke and myself have been granted push-access to the repository through a private team in the organisation. We can assume that @thefiddler did this, though it seems that he has not communicated with anyone (except @wcdeich4 through emails?).

As far as I can tell, nobody has admin-rights to the organisation or any rights regarding the website or forum - apart from @thefiddler of course.

While this is certainly a step forwards and allows us to continue the development of OpenTK, we still are missing a moderated/spam-free place to discuss things (next to GitHub that is). I am not sure if we care much about admin-rights to the organisation at this point (though this is bound to become relevant at some point in the future).

**Comment by wcdeich4** [comment]
If @thefiddler does not give us access to the website to de-spam the forums, we'll have to bug him later, but let's give him a little time since he's so busy working on his PhD - but it is essential to work on the site - the "issues" link doesn't even work now!

**Comment by tomspilman** [comment]
> we still are missing a moderated/spam-free place to discuss things

I suggest just using issues here on the repo to discuss design and tasks.  It works for us on the MonoGame project and I've never seen any spam.

Also could try https://gitter.im/ for a quick free real-time and message based chat.

**Comment by WardBenjamin** [comment]
I definitely recommend gitter as well, I use it all of the time. You can also use it with any irc client or their desktop client if you would rather not use the web version.

**Comment by cra0zy** [comment]
Gitter room created https://gitter.im/opentk/opentk, any further discussion on this subject should probably be done there.
