### ISSUE TITLE
 Windows.Forms+GLControl tutorial exception

### ISSUE THREAD

**Issue by osstekz** [opentk/opentk#371]
I downloaded binaries to a Win2008 Server (.Net4.) ) and successfully ran through the Open Toolkit Sample Browser examples. Very interested in Winforms-GLControl. Following the tutorial "http://www.opentk.com/doc/chapter/2/glcontrol?page=1", 
I created a simple Winforms test program.  When calling  InitializeComponent()...
this.glControl1 = new OpenTK.GLControl();
throws an exception
Unable to load DLL 'libEGL.dll': The specified module could not be found.

According to the docs, I understood libEGL was optional?
Any help appreciated. Thanks!

**Comment by wcdeich4** [comment]
Please download the latest code from https://github.com/opentk/opentk  recompile & use the files produced in the Binaries folder & let us know how that works.

**Comment by osstekz** [comment]
I've downloaded before posting, but compiling is not straight forward. I have VS2010 Ultimate and compiling the first project generates a lot of errors like:
Error	11	The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?)	D:\Public\Downloads\opentk-develop\opentk-develop\Source\Generator.Rewrite\Program.cs	51	16	Generator.Rewrite

**Comment by wcdeich4** [comment]
@cra0zy @amulware any ideas? 

@osstekz can you try a newer compiler, say VS 2015 Community?  I know Ultimate has the most features, but 2010 is pretty old; even w/ all it's updates, maybe that could be the problem.

**Comment by cra0zy** [comment]
Try compiling using Xamarin Studio.

**Comment by varon** [comment]
@osstekz - you'll need to do a NuGet package restore to get it to build.
Generally this is done from the command line with `./nuget restore`.

Based on the age, I'm going to close this for now. If you encounter trouble, please comment here so we can re-open the issue.

**Comment by ajos6183** [comment]
I am using the latest Nuget package on Windows 10 and getting the same exception. If I tell visual studio not to break when `System.DllNotFoundException` is encountered, then things work fine. What is the best solution to stop this exception? If possible, i prefer to stick to the Nuget package rather than having to compile it myself due to my lack of experience in this area, but i may go down that path if it's the only solution.

![image](https://user-images.githubusercontent.com/32379403/51875347-ae7ea200-23b8-11e9-8891-3de54a164b4d.png)
