### ISSUE TITLE
Opentk.com: "This account has been suspended"

### ISSUE THREAD

**Issue by sbrl** [opentk/opentk#381]
The website for this library, opentk.com, seems to have gone down. If you visit any page on the site, you get a "This account has been suspended" message. Here's the page I'm getting redirected to: http://opentk.com/cgi-sys/suspendedpage.cgi

This means that I can't browse any of the opentk docs online at all. I really need them too, especially since not 1 but _2_ of my university courseworks are using this library.

**Comment by wcdeich4** [comment]
@sbrl what documents do you need? Maybe we can send you copies? We are currently re-building the site & revitalizing the project.  @thefiddler @cra0zy @amulware any thoughts?

**Comment by sbrl** [comment]
@wcdeich4 Oh thanks! A copy of the API docs would be great.

**Comment by amulware** [comment]
Best short term idea I have for you is using the general OpenGL documentation, and 'guessing' what the related OpenTK functions and types are called. Mostly that works well enough (and it is actually how I work with OpenTK all the time, since there are much more OpenGL resources out there).
Not sure if this will apply to what you need exactly though.

@wcdeich4:
Not sure what else to add... Maybe there is some chance that we could get access to the domain eventually, and host/build our own site. Not that I want to shut @thefiddler out, but realistically.. it is just very difficult to do things this way, with him being gone.

My offer to host and moderate a forum (and website) still stands, for whatever it is worth - but only if you are all standing behind that of course.

**Comment by sbrl** [comment]
Perhaps the docs could be hosted temporarily with github pages.

@amulware Thanks for the suggestion. I've taken a look, but I keep getting confused between the different data types and what each method return via `out` and `ref`. I'm not very experienced at this kind of thing :(

**Comment by johnnyontheweb** [comment]
@wcdeich4 I need the reference manual me too, if possible. 
Unfortunately, I never seen the site before, and I'm guessing if documented vb.net samples are also available.
Thanks

**Comment by ala53** [comment]
Additionally, as a temporary measure, you can use the WayBack machine ( http://web.archive.org/web/20160315012704/http://www.opentk.com/ ) or Google's cache ( cache:opentk.com in chrome).

**Comment by sbrl** [comment]
@ala53 Yes you can, but the really useful pages aren't actually indexed :(

**Comment by ala53** [comment]
@sbrl Wayback seems to have most of the docs indexed (e.g. http://web.archive.org/web/20150217225220/http://www.opentk.com/doc/hacking/bindings ) but there's a lot of spam on the pages you have to search through.

**Comment by wcdeich4** [comment]
Funny opentk.com went down now; we were just talking about taking it down & making it re-direct to https://github.com/opentk/opentk/wiki   

Also see https://gitter.im/opentk/opentk 

starting at http://web.archive.org/web/20150217095213/http://www.opentk.com/doc/chapter/0    and then working forward seems like a good place to start for documentation. 

@sbrl a lot of times there are 2 versions of the same method - one that uses out & ref and another that calls the out/ref version.  This is because using out & ref can be more efficient, but we often want a more "traditional" method that passes parameters by value instead of reference - so the "traditional" calls the out/ref method which actually does the real work to obey the DRY (do not repeat yourself) principle (but occasionally there are places where we broke the DRY principle & there are 2 independent versions of the same function & very rarely they may even have different code inside them but should still return the same result - hopefully - it was only recently @Manuli and myself added a unit project) 

When you see "throw new NotImplimentedException();" that is b/c the source is compiled to a .dll
then a separate program patches that .dll to bind the OpenGL function calls in a way that is faster than can be done directly in C# code - but @thefiddler would have to tell  you more about it, it's not a part of the code I have worked with myself.

**Comment by wcdeich4** [comment]
@johnnyontheweb & @sbrl if have specific questions let us know & we can post them to https://github.com/opentk/opentk/wiki

**Comment by sbrl** [comment]
@wcdeich4 Starting a new wiki sounds like a great idea! I've been annoyed at how hard it is to debug shaders for a while now, so I thought I'd try my hand at writing a little tool to help me along (no, I can't use NSight, that requires admin permissions which I don't have at University). Are there any examples of `GL.GetShaderSource`? I can't seem to figure out how it works?

**Comment by sbrl** [comment]
Hrm. Maybe I should take a little look at those overload then. That link also appears to be very helpful. I think I might download those pages and stitch them together into a PDF or something.

**Comment by varon** [comment]
Probably the best reference for the OpenGL is the C documentation - OpenTK is pretty faithful to it.

Also make sure you have the documentation XML file (which is very comprehensive) so your IDE can provide basic info.

Finally, you can always ask questions on the [OpenTK Gitter channel](https://gitter.im/opentk/opentk).

**Comment by sbrl** [comment]
@varon I've got intellisense, but it isn't as comprehensive as I would like. The OpenGL C documentation is practically useless, as I keep getting the parameter types confused.

**Comment by gwicksted** [comment]
@sbrl why not have docs permanently hosted in the GitHub wiki?  Then point to it, the source, compiled binaries, external tutorials, etc. from opentk.com?

**Comment by sbrl** [comment]
@gwicksted Having the docs hosting on Github would be great! I don't think I've got access to the orginal docs though, and wouldn't know where to start if I did.

**Comment by sbrl** [comment]
I've downloaded and converted the tutorial into an epub ebook for temporary purposes only. Here's a link: https://transfer.sh/hzknj/the-open-toolkit-manual-unknown.epub - it'll be available for 2 weeks.

**Comment by cra0zy** [comment]
Website is live again.
