### ISSUE TITLE
Passing uniform array of vec3

### ISSUE THREAD

**Issue by alakanu** [opentk/opentk#403]
Hey all, 
I've seen [this](http://www.opentk.com/node/3584), and I was wondering whether that overload had been tested, I am currently using the OpenTK.Next NuGet package.

**Comment by varon** [comment]
Thanks for the question, @alakanu.

From what I can tell, there's still an outstanding PR for it (See #95), but unfortunately it needs testing, which nobody has done yet.

Because of this, you've got 3 real choices:
 1. Test the methods added in #95. If it works, we can merge it and get it into the next package update.

 2. Copy the Vec3 array to a float array and use the existing API.

 3.  If you really must avoid allocating memory, you can probably gamble on the `StructLayout` attribute of `Vector3` and [try to reinterpret cast the pointer](http://stackoverflow.com/a/479767).

**Comment by alakanu** [comment]
Thanks for the answer @varon ,
I think I'll go with the option number 2 for now. However I'd like to help, even though I'm a noob. Hence I'm gonna do some research to understand how can I actually test it (yes, I'm at that level lol).
