### ISSUE TITLE
Remove the use of default parameters

### ISSUE THREAD

**Issue by WernerWenz** [opentk/opentk#439]
### Description

OpenTK uses default parameters at serveral locations.
For ex. [here].(https://github.com/opentk/opentk/blob/d50c2fcea0696d3cc82aeb339e15c049405129ba/src/OpenTK/Math/Matrix3.cs#L344)

This was probably not intended, as looking for example at the GameWindow ctor one will find several overloads rather than default parameters
### Reasons for the change

Default parameters have to be supported by the actual language OpenTK is used from within.
#### Directly replace all default parameters by proper overloads

This is the most simple and straight solution. 
#### Use Cecil to automatically generate the overloads in a post process

Cecil is already used in the "rewrite" process. In a similar fashion the overloads could be automatically generated.
All code could then be refactored to use default parameters.

**Comment by ThomasD13** [comment]
Example for languages which does not support default parameters: C++/CLI
But if this language is still used widely is another question.

**Comment by hokb** [comment]
Voting against. When used carefully default parameters can prevent from code bloat. It is one nice feature and perfectly legal to be used. I see little to no reason to replace it by multiple overloads. Please elaborate.

**Comment by varon** [comment]
So far, it seems like the only one with an issue is C++/CLI.

Is anyone else experiencing this issue in another language?

**Comment by cyotek** [comment]
http://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/
https://lostechies.com/jimmybogard/2010/05/18/caveats-of-c-4-0-optional-parameters/

Old posts, but sums up some of the issues. I'd rather have the overloads and never use optional parameters in a public API, it's safer. I fail to see how it is code bloat, especially from a consumed API.

**Comment by hokb** [comment]
Changing the value of an optional parameter makes consumers of the library having to recompile their code if they used the affected method without providing a value for the optional parameter themself *and if they want to move to the new default behavior*. The way it works prevents a breaking change for the user. You cannot know if the user provided the parameter or not. The way it is compiled now assumes she did provide the value, always. So she keeps getting the old behavior (no breaking change) – as long as she does not recompile. Otherwise, the case of multiple overloads would introduce a breaking change since here, you forward a call to a less specific method internally to the most explicit method and specify the default parameter inside the dll code. But for the caller the code does not the same anymore. 
Commonly, you don't update a dependency once you went to production stage. You only do as long as you are in development. At least I don't know a single customer who would. This is especially true for a dependency which just changed its behavior. 

Are there other issues with optional parameters?

**Comment by varon** [comment]
@cyotek - Thanks for chipping in here. I agree the .Net system isn't very elegant, but it's already implemented by every relevant language. To respond to those blog posts, here are a few thoughts:

1. The first argument is predicated on the fact that upgrading a dependency without recompiling your code causes a breaking change. I do have to ask though - why would you _ever_ do that? It's frankly insane to randomly upgrade a dependency without recompiling it, because of point 2.

2. If a dependency upgrade causes a compilation error, that's a good thing. It ensures that the user is aware of the error and can make a decision about how to address the API change. This is exactly why you would need to recompile your code against the updated dependency.

You guys need to remember here, we're not working with vast, enormous legacy C systems, but instead a modern, flexible language with clever dependency management and a very quick compile cycle. Recompiling isn't something to be afraid of, but rather embraced as a consistent part of the process, and a critical line of defense against simple errors.

To make my opinion on this a bit more clear:

Supporting C++/CLI is not something I believe OpenTK should have as a goal. In that language you could simply use the native bindings anyway.

I'm explicitly against any more use of IL rewrites, and in fact would like to remove our rewrite stage from the compilation entirely. It's black magic that I don't think anyone currently on the OpenTK team fully understands.

Given these points, and the fact that most of our API is 'very stable', I'm strongly in favour of keeping the optional parameters as is.

@hokb you're addressing the case where we've made an old parameter optional. In our case, we're discussing the usage of optional paramters versus overloads.

**Comment by hokb** [comment]
@cyotek Thanks for the clarification. I was referring to the blogpost arguments and agree with everything you said.

**Comment by varon** [comment]
Thanks for the discussion guys. I'm going to go with keeping things as they are.
