### ISSUE TITLE
Windows DPI scaling is causing the GameWindow size to scale, which is correct, but there is no way to find out the unscaled size of the GameWindow.

### ISSUE THREAD

**Issue by jamestalton** [opentk/opentk#47]
Reported Width and Height of GameWindow is scaled by the Windows DPI scaling.
This is correct, but there is no way to know what the non-scaled Width and Height are set to.  This is useful when saving the window size and position.

Example: Create a window with size 640 by 480.  Windows desktop DPI scaling is set to 150%.  GameWindow width is 960 and height is 720 which is correct. If we save those values and use them upon next start, the window will grow another 150% in size.

Maybe there could be new properties such as UnscaledWidth and UnscaledHeight.

**Comment by kaalus** [comment]
IMHO leave it as is for compatibility and instead do 2 things:

- Document which value each function takes/returns (something that's already mostly covered by this topic)
- Allow users to access scaling value used, which AFAIK is currently unavailable. This will allow anybody to easily convert between scaled/unscaled units as needed. One multiplication/division in a few places is not the end of the world, if one knows what to multiply by!

**Comment by jeske** [comment]
You cant "leave it as is" because right now you can only make hidpi opentk apps work properly on *either* mac or windows. The goal should be for the common opentk source patterns to work correctly out of the box with hidpi or not.

Option 1 will give opentk apps sane behavior on both mac and windows, hidpi or not. Windows recommendations should be ignored as their hidpi support is still a mess.

It's just important to also expose the raw unscaled desktop res, window res, and coords.. So apps that want to custom support hidpi can do it. (Best practice is to render 3d at a lower resolution, but 2d at native screen resolution.. Which takes sme custom cosing)

**Comment by amulware** [comment]
We have been having some issues with this as well, but so far I have not been able to fix the problem apart from telling Windows not to use DPI scaling in the compatibility settings of the executable.

The workaround @thefiddler posted above also does not seem to do anything for us. The window reports to be the same size that I told it to be, even though I have scaling set to 200% right now. (And the window is ridiculously big and blurry accordingly.) And this is the same, whether I tell windows to enable or disable scaling for the application. (This is all on Windows 8.1.)

Regarding the two options given, from a game developer's perspective, I would much rather have control over my window on a per-pixel basis, so that I can render as pixel-perfect as I want. If there is up-scaling to be done, I would prefer being in charge of that myself (and in terms of games, especially on PC, exposing relevant settings to the user; a significant number of them prefers to be in full control of their games' settings).

I can see @jeske's point though and as long as enough info is exposed for me to do my own thing, I am fine.


One other point, that may or may not be related (if you think it is not, let me know and I'll make another issue):
We have a couple of customer complaints reporting that our game runs in less than full-screen size when they toggle on fullscreen mode. I use a bunch of custom code for that, but in essence I get the bounds of the DisplayDevice and set the bounds of my window to the same value.
What confuses me is that when I set my scaling to 200%, the window gets much larger than my screen. The users in question report that their window is too small though, which sounds like they have less than 100% scaling, which is not supported by Windows however. Further it makes little sense to me, since they would essentially be unable to read any text on their screen.
The only other bit of information I have right now is that the people in question all seem to use screens with larger than fullHD resolutions. I do not see what could go wrong with that though. While I cannot test on larger than fullHD myself, I can resize the window to be larger than that, and neither OpenTK nor OpenGL have any issues with that.

**Comment by Frassle** [comment]
I've got a Win7 desktop and Win8.1 laptop at home so I can do some DPI tests on Windows. Looks like some [MSDN](https://msdn.microsoft.com/en-us/library/dd464646(v=vs.85).aspx) reading is in order.

If others can help with the OSX and Linux stories (especially OSX, I have a Linux box at work I can test on but no access to OSX machines), we can see about trying to unify behaviour across all platforms.

**Comment by jeske** [comment]
Agree with @amulware that it should be possible to see raw (unscaled) values, and control pixel perfect results. 

The reason I support option-1 (using scaled pixels in all the default APIs) is that it produces the most sane behavior on the widest variety of systems and hardware. When you have *real* hidpi displays, most games will not run reasonably with HiDPI 3d surface sizes, because of fill rate limits. For example, the MacBook Pro Retina is a laptop with 2880x1800. The mobile GPU can't push that many pixels in 3d rendering at reasonable FPS. The same is true of HiDPI windows laptops. 

An important subtlety is how to detect HiDPI on windows (and eventually Linux), and when to treat everything as Native Pixels vs HiDPI scaled. For example, a user who sets the Windows UI Scale to (say 110% or 120%) should get a native-pixels OpenTK Game Window. However, one with 180% or 220% is most-likely on a HiDPI display and should get a scaled window. Alternatively, I believe windows has a DPI value you can query, independent of UI scaling. However, I'm not sure if that is reliable.

**Comment by wcdeich4** [comment]
Should this issue thread remain open?

**Comment by varon** [comment]
We've had a similar report in Gitter very recently, and it's going to become more significant as displays continue to improve. We should leave it open, I suspect.

**Comment by mcmonkey4eva** [comment]
Definitely still an issue! To be fair, it's an issue with a massive portion of windows software. I'd just like to not have it be an issue for /my/ (OpenTK-based) windows software.

**Comment by varon** [comment]
Could really do with a contribution here, fairly testable and intermediate difficulty.

**Comment by mcmonkey4eva** [comment]
Based on fiddler's post, it would have to be a bit carefully designed with simultaneously Windows and Mac in mind - or perhaps a solution created that carefully only applies to one of the two and leave the other for someone else to do?

**Comment by jeske** [comment]
It looks like [Windows DPI scaling support](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx) has changed from win 8 to 8.1 also, so windows now has 3 cases. 

1. <= windows xp - no dpi scaling
2. windows vista to 8 - system-wide dpi scaling
3. widnows 8.1+ - per-monitor DPI scaling

It also looks like the best way to tell windows you are dpi aware is in the application manifest, which means it really is up to the application author. There is a [SetProcessDpiAwareness()](https://msdn.microsoft.com/en-us/library/windows/desktop/dn302122(v=vs.85).aspx) call which could be used in OpenTK for `GameWindow`, but since it has to be called before **any** Win32API call which requires scaling, it could fail if the user application creates anything visual before `GameWindow`.

It would be safer for OpenTK to call [GetProcessDpiAwareness](https://msdn.microsoft.com/en-us/library/windows/desktop/dn302113(v=vs.85).aspx) to determine what the application author has put in the app manifest, and then have OpenTK act appropriately. 

There is also a new event WM_DPICHANGED for responding to [dynamic DPI changes](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#supporting_dynamic_dpi_changes), such as when the user changes the system or monitor DPI, or when the window moves to a monitor with a different DPI. 

------

I'm not 100%, but I'm leaning towards thinking the right thing to do on Windows is:

1. change OpenTK DisplayResolution, and MouseState to use scaled pixels (i.e. match MacOS)
2. provide a toggle for whether GameWindow uses scaled or native pixel dimensions for the OpenGL surface, default to scaled pixel dimensions
3. expose the DPI scaling factors per display/window
4. expose the WM_DPICHANGED event per window

------

As for implementing 4 on the mac, there is `CGDisplayRegisterReconfigurationCallback`, and `[NSWindow windowDidChangeScreen]` or `[NSWindow widowDidChangeBackingProperties]` via [NSWindowDelegate](https://developer.apple.com/documentation/appkit/nswindowdelegate)

**Comment by aramazhari** [comment]
Hello, 

I know this is an old issue, but if you're creating you're compiling on Visual Studio, you can simply set this from the project properties which will take care of everything:
https://nlguillemot.wordpress.com/2016/12/11/high-dpi-rendering/

This simply tells visual studio to create a manifest file next to your executable that makes it "Dpi Aware"
I've had the same issue with SDL2 and this resolved it for me.

Just my two cents.

**Comment by jeske** [comment]
It doesn't "fix the issue" access windows and mac..  it just works around
the issues for windows only software.

**Comment by aramazhari** [comment]
Have you tried the link I provided for mac? There is a similar setting in xcode which does that (more info on that link).

Also notice the word "Windows DPI" in the title of this issue.

**Comment by jeske** [comment]
I dont use SDL because i want cross platform deployment without native dependencies.

In the past, i have tried the manifest settings on mac and windows, but opentk handles scaled and unscaled resolutions differently on mac and windows, as described in fiddlers post.

**Comment by george-tsiros** [comment]
sooo i'm kinda lost here
is it possible to request a width * height window ?

**Comment by varon** [comment]
Should be fixed in 4.x
