### ISSUE TITLE
Odd issue: native code memory leak and slowdown / How do I debug this...

### ISSUE THREAD

**Issue by mcmonkey4eva** [opentk/opentk#474]
I have the most interesting issue I've just discovered in my project...

There's a small-but-growing memory leak and matching slowdown-with-time.

Any OpenGL calls will lag at random in process timings, though most of the weight is in Finish()

I'm not sure what I did or how I did it but /native/ memory is leaking. (IE, NOT CLR memory!)

CLR Memory was at a static 1.2 GB while I watched total process memory go above 4 GB within a few minutes of run-time...

The question is, how do I debug this?

From DebugDiag 2r2 (Windows memory debugger)

`nvoglv64!DrvPresentBuffers` with varying offsets did a TON (in the millions) of allocations.
`nvoglv64!DrvValidateVersion+9244` allocated several gigs of memory.

I don't want to call this a driver bug, as I assume it's something I've done wrong in my code that's triggering this... so, question again: In a large project, how does one debug this sort of situation most effectively?

### Related information 

Windows 10 64-Bit
Native backend
OpenTK vlatest off github
Standard windows .NET framework 4.5

**Comment by winterhell** [comment]
Can you make a test case project that does the memory leak?
I can make guesses as to what is the cause but you never know.

**Comment by mcmonkey4eva** [comment]
If I manage that, I'd either not know OpenGL particularly well (and think I do), or be the victim of a driver bug...
It's gotta be some complex thing somewhere deep in my code.

I'm not asking for an answer "What's causing this" I'm asking for tools and techniques to better myself answer what's causing it!

**Comment by mcmonkey4eva** [comment]
Update: Found the leak, accidentally lost the code to Destroy some vertex buffers and their owning vertex array.
So they just kinda compiled up.

... which leads to a new question
Why is their mainline RAM side allocation for things that I would have thought would be in vRAM?
That might be a driver-specific oddity based on the locations it was allocated from, actually.

Still, question as to how to debug better stands!

**Comment by winterhell** [comment]
The driver keeps copy for most if not all textures and graphical objects in the system RAM, so that when you run out of video memory and a program needs more, oldest resources can be trashed. Then when you need them again they are reloaded. This is why when you exceed the memory limit, your performance plummets.
As to when it need the free space, why does the driver not transfer only the necessary resources back to the RAM? Maybe it is a safety concern, or calculated optimization so that the performance doesnt plummet even further.
I think there is a thing called resident textures, but those are dangerous.
On devices where the video and system memory is shared, like Xbox 360 or Android devices, there is likely just 1 copy of the resources.

**Comment by subchannel13** [comment]
About a question for tools or technique for troubleshooting issues like this, I'd recommend GLIntercept. It's OpenGL32.dll wrapper which logs OpenGL calls and warns you in the end if there were unreleased resources. It would have warned about leaking VBOs and VAOs.

**Comment by mcmonkey4eva** [comment]
Oooo, thanks! Traced that to https://github.com/dtrebilco/glintercept and it and its "similar" links are exactly what I was looking for!
