### ISSUE TITLE
Namespace clashes on IOS

### ISSUE THREAD

**Issue by tzachshabtay** [opentk/opentk#479]
When using OpenTK in a Xamarin IOS project, there are namespace clashes due to the fact that a lot of types in IOS were taken directly from OpenTK (for example, Vector2) without changing the namespace.
The only workaround seems to be using extern alias (on either Xamarin.IOS or OpenTK) but that's really making things look ugly and unmaintainable.

I originally opened a bug for Xamarin to change their namespaces (https://bugzilla.xamarin.com/show_bug.cgi?id=52169) but they refuse as it will be a big breaking change. 
They recommend for OpenTK IOS to refer to the Xamarin.IOS and use it's types instead of including them directly.

**Comment by varon** [comment]
I'm not sure there's anything we can really do here. Any ideas?

**Comment by varon** [comment]
Very likely related to #494 as well, just the iOS version.

**Comment by jeske** [comment]
Could we separate the conflicting types into another assembly, and manually load either that or Xamarin.iOS based on platform?

**Comment by varon** [comment]
The problem is our function signatures in the stuff that use the types, such as `GL.Uniform3` would need to change as well.

We definitely want to use our types, as they're vastly more tested, comprehensive and consistent than the built-in ones. It's just a question of figuring out how to get our stuff working.
