### ISSUE TITLE
String GetXYZ functions should use maxLen instead of sb.Capacity

### ISSUE THREAD

**Issue by UnknownShadow200** [opentk/opentk#517]
See issue #515 for example

This can lead to memory corruption due to 'max length' / 'buffer size' being passed to OpenGL, whereas the actual size of the unmanaged memory is only sb.Capacity

**Comment by varon** [comment]
Nice spot.

If you can PR in a fix, I'll merge without any trouble.

**Comment by UnknownShadow200** [comment]
Bit busy currently, will look at making a pull request when I get the time to look at how generator works and can be fixed for this.

**Comment by varon** [comment]
@Nihlus  - this looks to be rewrite/gen.

I spent about half an hour looking over it, shouldn't be too hard to figure out where this is.

**Comment by UnknownShadow200** [comment]
Oops I forgot about this. From what I recall, I looked for parameters
sb.Name + "Length", "length", "bufSize"

If I found any parameters, i'd use ldarg instead of call for sb.Capacity

**Comment by Frassle** [comment]
Copying description and proposals from #204.

================================================================================
glGetActiveUniform takes an integer capacity paramerter and also a StringBuffer. Internally we allocate native memory equal to the size of the string buffer (by calling StringBuffer.Capacity), if the capacity of the string buffer does not match the integer capacity parameter passed in we get a mismatch of how much memory is actually availible and how much OpenGL thinks it can use.
Methods like this should either:

A) Not include the integer capacity parameter and only go by the StringBuffer.Capacity (this does mean you can't limit the amount written without reallocation)
B) Use the minimum value value of the capacity parameter and StringBuffer.Capacity to actually pass to OpenGL. This is arguably confusing behaviour.
C) Give an error when capacity parameter is greater than the StringBuffer.Capacity. Maybe only in debug builds to keep release builds fast.
D) Resize the StringBuilder to match the requested capacity inside the called function.
E) Create and return a StringBuilder, and not require it as an out parameter.

Since StringBuilders auto resize in managed code, either of these options allow the function to handle this detail without extra code in every calling function.

================================================================================

Can be a bit more specific now. Looking at #515 the function used was `GetActiveUniform`:
```
int program, index, bufsize, length, size;
ActiveUniformType type;
StringBuilder name;
GL.GetActiveUniform(program, index, bufSize, out length, out size, out type, name);
```
The interesting parameters here are bufSize, length and name. They pretty much match the underlying C API except in that case name is a char pointer.
I'm kinda inclined to remove the length attribute, instead clients should look at name.Length.
As for bufSize, we've got a load of options above. I think option D is probably the easiest for people to use (make sure name.Capacity is at least bufSize inside OpenTK), but does have the downside of us doing an allocation. Need to make sure people who are GC pressured know about that so they can set name.Capacity to a large enough value before hand.

As for actually doing this. It's probably quite involved. I think there's two parts:
A) Change Rewrite to set name.Capacity to max(name.Capacity, bufSize) and to set name.Length to length after the native call.
B) Change Bind to not emit the `out length` parameters, as can just use name.Length. That does break the API a bit but we seem to be on a breaking spree at the moment anyway.

A should defiantly be done so I'll have a look into that now. I'll leave B for some discussion.

**Comment by Nihlus** [comment]
@Frassle If the specification requires a certain number for certain length parameters, I see no reason not to go for safety and compliance over what marginal speed increase there might be when the checks are omitted. 

However, I think the stringbuilder issue takes precedence, since the former is an improvement while the latter may cause memory corruption in its current form.

**Comment by Frassle** [comment]
The former can cause memory corruption as well. Nothing stopping the user passing an array of size 2 to an OpenGL method that will write 4 values back. Although I agree the StringBuffer is probably more likely to cause issues. My reason for doing them in the order I described is I hope it will be a lot easier to understand and review the code in that order, I will get to StringBuffers quickly though!
