### ISSUE TITLE
About quaternion operators

### ISSUE THREAD

**Issue by nthalpy** [opentk/opentk#573]
I am currently using OpenTK 2.0.0, and in Quaternion.cs, there are some methods which multiply quaternion and scalar, like
```
public static Quaternion operator *(float scale, Quaternion quaternion)
public static Quaternion operator *(Quaternion quaternion, float scale)
```

I know this methods are useful for implementing slerp, or some animation related stuffs. But I found when handling quaternion, vector, and scalar at once, the order of operation matters, and wrong orders can make different result like:

```
Quaternion quat = new Quaternion(3, 4, 5);
Single scalar = 6;
Vector3 vec3 = new Vector3(7, 8, 9);

Vector3 result1 = quat * scalar * vec3;   // {(93.71551, -632.897,  -425.2697)}
Vector3 result2 = quat * (scalar * vec3); // {(56.45258, -58.81617, -18.37828)}
```

I sometimes make this mistake, and makes wrong result, and waste times at debugging codes. So I think we should remove method
```
public static Quaternion operator *(Quaternion quaternion, float scale)
```
to prevent making mistakes.

**Comment by Nihlus** [comment]
Unfortunately, it's the cold hard truth that multiplication order matters when working with graphics programming. It would cause even more confusion to only allow multiplication by scalar from one side, since the order does not matter for a scalar multiplication.

Removing the suggested method would break numerous other applications (just about every single one using quaternions) in ways that would not be directly apparent - it might still compile, but the mathematics would start acting in unpredictable ways similar to the problem you're experiencing. I'm afraid you're just going to have to be more explicit about your multiplications in code.

**Comment by varon** [comment]
@Nihlus  - I think what he's saying is that scaling a quaternion isn't really something that client programmers frequently need to do. The intention behind this is that * only applies to quaternion/vector, while the `Quaternion.Scale` function might be used for quaternion/float.

We should look at what unity and Unreal do, and then make a change to the availability of those operators.

**Comment by Nihlus** [comment]
Unreal supports this behaviour, and it's a well-defined standard
mathematical operation. Unity does not, but it doesn't provide quat-vector
multiplication either.

The current implementation is what you would expect from a purely
mathematical standpoint, and as I mentioned, changing it would have
nonobvious side effects.

**Comment by varon** [comment]
Cool, no worries. Makes sense to keep it as-is.
