### ISSUE TITLE
Input Bug : Unmapped gamepad DPads get stucks at Left

### ISSUE THREAD

**Issue by NinjaFighter** [opentk/opentk#576]
### Description

Unmapped Gamepad DPad always returns "{L}" when centered.
If I press right direction it returns "{R}"
If I press up direction it returns "{U}"
If I press down direction it returns "{D}"

Everything is ok, except when I don't press any direction.

Looks like it only happens on Unmapped Gamepads.

### Related information 

* Operating system: Windows 7 Professional
* SDL or Native backend: Native (?)
* What version of OpenTK (Installer, NuGet, Source Code): NuGet OpenTK 3.0.0 pre
* What runtime (.NET Framework, CoreCLR, Mono): .Net 4.5

**Comment by varon** [comment]
We've had quite a few fixes relating to gamepads and input recently.
@Nihlus or @leezer3 can probably suggest if this is already fixed.

You could also try build from source if you want to give this a go yourself

**Comment by leezer3** [comment]
This sounds like the behaviour prior to the 7-position hat fix, so I'd guess this should probably be fixed.

What gamepad?

**Comment by NinjaFighter** [comment]
This happens with my "Ps2-like" usb Kolke and a standar Twin Usb Joystick.
Those ones works very well at windows configuration and other games.
As I said previously, looks like it happens to every Unmapped Gamepads (for example, Xbox 360 controller works perfectly (and it's mapped)).

**Comment by leezer3** [comment]
The mapping is neither here or there.
All that does is to assign the axis / button numbering so that it's consistant & in line with the SDL2 gamepad database. (e.g. Thumbsticks on two consecutive axis etc)

We read the raw HID data provided by the pad / stick & don't use most of the Windows interfaces directly.
Again, try compiling from source and report back if the issues are still there.
I will try and get my hands on a cheap PS2 clone pad though, as most of these will normallybbe using the same HID chip.

**Comment by NinjaFighter** [comment]
I compiling last source and it works perfecly now! Thanks!
I wonder why this version is not the nuget package one!

**Comment by varon** [comment]
Thanks for the prompt reportback, @NinjaFighter.

It's not in Nuget because we still need to work on our release management, and the current version is pretty stable anyway.
