### ISSUE TITLE
Win32 exception 0xc0000374 occurs randomly FileDrop event

### ISSUE THREAD

**Issue by TGEnigma** [opentk/opentk#626]
### Description

Program randomly, but frequently, crashes with a Win32 exception code 0xc0000374 when the OnFileDrop ( or event handler ) method is called.

### Repro steps

```
using ( var window = new GameWindow() )
{
      window.FileDrop += (s, e) => { };
      window.Run();
}
```

Using the above snippit, drop a file on the window a handful of times and it will eventually crash.

### Expected behavior

Shouldn't crash. Exception also can't be caught ( or at least through any normal means ).

### Actual behavior

Inevitable crash of the program.

### Related information 

Windows 10
Native GL
Built from source today.
.NET Framework

**Comment by Nihlus** [comment]
@VPeruS This is your department, I think.

**Comment by Frassle** [comment]
From MSDN for [DragQueryFile](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776408(v=vs.85).aspx):
> the return value is the required size, in characters, of the buffer, not including the terminating null character.

We've declared DragQueryFile as auto char set:
```
[DllImport("shell32.dll", CharSet = CharSet.Auto)]
internal static extern uint DragQueryFile
```

And finally the code that uses this allocates space for the string by calling AllocHGlobal with the return value of DragQueryFile + 1 for the null character.
```
// Don't forget about \0 at the end
uint fileNameSize = Functions.DragQueryFile(hDrop, i, IntPtr.Zero, 0) + 1;
IntPtr str = Marshal.AllocHGlobal((int)fileNameSize);
```

Which all looks reasonable *except* because we use auto char set this will use the unicode version of DragQueryFile (On most versions of Windows except XP) which is 2 bytes per character. That's probably the root cause of the corruption.

**Comment by wcdeich4** [comment]
Is it possible to add an if to test how many bytes per character in the environment where the code is running>

**Comment by VPeruS** [comment]
It isn't big deal how much to allocate, it will be almost immediately freed.

**Comment by UnknownShadow200** [comment]
Testing how many bytes per character in the environment probably isn't that important - it doesn't really matter if we overallocate by always using 2 bytes per character, since filenames are comparatively small anyways.
