### ISSUE TITLE
Crash on Mouse.GetState() when mouse is  unplugged on MacOS

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#656]
### Description

![screen shot 2017-09-28 at 4 47 01 pm](https://user-images.githubusercontent.com/762006/30970180-bdc6e30a-a464-11e7-9544-ff956c9927fb.png)

### Repro steps

Call Mouse.GetState() during render frames, then unplug the usb cable/receiver of your mouse

### Related information 

* Mac OS Yosemite 10.10.5
* Native
* NuGet 2.0.0
* .net framework 4.5.2

**Comment by Frassle** [comment]
The DeviceCollection object just used the underlying List<T>'s iterator. This meant that when we nulled out a list entry (rather than removing it to save on memory shuffling) that null entry was still returned when doing a foreach over the DeviceCollection. Easy fix of implementing a custom iterator that skips nulls in the list. Will have a PR soon.
