### ISSUE TITLE
OpenTK Documentation

### ISSUE THREAD

**Issue by jakabszili13** [opentk/opentk#672]
I know its not an issue with the API, but i didnt know where else to ask this.
I found a manual about OpenTK, bug i would be interested in looking through the documentation as well that you have/had on www.opentk.com, but the whole website is down. Any information on when it might be up again, or where else would i be able to find it?

**Comment by UnknownShadow200** [comment]
The [web archive](https://web.archive.org/web/20150325224427/http://www.opentk.com/doc) has some of the documentation from opentk.com.

**Comment by Nihlus** [comment]
Unfortunately, we no longer have access to the opentk.com hostname, so that site will not be returning. We do have https://opentk.github.io/ now, which is the replacement. As for the manual, it was hosted on the old site and is only available through internet archiving. Furthermore, it's severely outdated and needs updating.

See #599.

**Comment by daerogami** [comment]
@jakabszili13 I have a pr in the works that will start addressing this issue in short order.

**Comment by wcdeich4** [comment]
@daerogami thank you for all your hard work.  I believe I still have a copy of the ebook you made from the old website if that helps, although I know there have been significant code changes recently.
