### ISSUE TITLE
There is no KeyModifier for the Cmd Key on Mac os

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#757]
### Description

The KeyModifiers enum only contains shift, ctrl and alt keys, but not Cmd. This prevents me from capturing a keyboard copy/paste event. 

The Modifiers attribute of the KeyboardKeyEventArgs is also 0

### Related information 

* Mac OS High Sierra
* Native backend
* 3.0 I think

**Comment by leezer3** [comment]
It's being mapped to the Left Win key here:
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/MacOSKeyMap.cs#L243

Now, IMHO that's wrong, and we should actually add the command key to the modifiers enum.

On Windows, it's mapped to the Windows key, but I'm not sure without testing with physical hardware whether the raw HID data is something different to a plain PC keyboard & Windows internally maps it or what....
https://github.com/opentk/opentk/pull/759
This is untested as I've got no native hardware, but simple enough that assuming the enum test value is correct it ought to work OOB (Yeah I know, famous last words).....

**Comment by tyronx** [comment]
Oh, what I forgot to mention: Pressing the Cmd Key alone also doesn't seem to fire a keydown/press event in the first place.

**Comment by leezer3** [comment]
Whelp, you're entirely right....
That led me to find the issue; OS-X transmits the modifier keys as an entirely separate window pointer type, rather than as a standard keypress event,

Please test the PR with the second commit included, *not* the first- This actually makes it work (and fixes a stupid C+P bug with ALT).
It's also added the Command key into the enum, as I decided that was the best way to deal with things.

Have done some minor testing on a OS-X VM using a standard Windows keyboard (forgot I had that one...), and that's working as expected.
I've also done some testing on Windows, which appears to work as expected. As I've noted in the PR though, modifiying the Keys enum needs some comprehensive testing to make sure there isn't anything stupid going on with casting....

**Comment by Nihlus** [comment]
Fixed in #759
