### ISSUE TITLE
Color4 and Vector4 should be compatible

### ISSUE THREAD

**Issue by ahmetsait** [opentk/opentk#833]
Currently there is no built-in conversion between `Vector4` and `Color4`. It is highly convenient to be able to use Vector and Color structures interchangeably similar to how GLSL colors are effectively just vectors.

Also, Color4 doesn't have `[StructLayout(LayoutKind.Sequential)]` attribute which makes it dangerous to pass it to OpenGL functions.

**Comment by devvoid** [comment]
Theoretically, should this just be implemented as an implicit conversion between the two types? That, and add the proper StructLayout to Color4. I have a local fork that does just that, but I haven't had time to test it.

**Comment by varon** [comment]
This definitely needs to have the struct layout applied to it.

>Theoretically, should this just be implemented as an implicit conversion between the two types? 

I'm not sure we'd want to go the implicit route. Implicit involves calling a method, and copying it as a parameter. A reinterpret cast would do the same thing with zero cost. The trick is figuring out how to expose that to 'Safe' C#.

Another idea is to avoid casting it as much as possible. We should ensure that the bindings generator can take Color4 wherever it accepts a Vector4. It probably does this already, but @Nihlus would have the answer to that.

**Comment by devvoid** [comment]
I'll submit a PR to add the struct layout in a moment, and I'll hold off on the actual compatability until Nihlus gives his two cents.

**Comment by FreezyLemon** [comment]
```
C#, Visual Basic, and C++ compilers apply the Sequential layout value to structures by default.
```

[source](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute?redirectedfrom=MSDN&view=netstandard-2.0)

**Comment by jvbsl** [comment]
I'm not too sure, but it could be possible that the Jitter optimizes an implicit conversion. Because it should be inlineable at least, and after that it depends on used C# Code.
Perhaps with pointer conversion it works in Assembly to be optimized to a simple reinterpret of data.

**Comment by MutterOberin** [comment]
I fully support this for being part of OpenTK. Also a .NET Color to Vector3 / Vector4 implicit operator would be nice.

**Comment by devvoid** [comment]
Picking this up again after working on other things for a while, trying to figure out how it should work.

The closest thing to a reinterpret\_cast in C# is pointer casting, right? From what I've found, reinterpret\_cast is just an abstraction over pointer casting anyways. Right now, what I'm trying is as follows:

```cs
public Color4 AsColor4Unsafe()
        {
            unsafe
            {
                fixed (Vector4* ptr = &this)
                {
                    return *((Color4*)ptr);
                }
            }
        }
```

This is just a test, but it seems to work in a minimal testing environment. It avoids allocating a whole new struct, but it's just the original data being interpreted differently, which could cause confusion to end users. This is all assuming that's even what Varon meant to begin with.

**Comment by ahmetsait** [comment]
I don't think constructing a new Vector4 would be a big issue since it will likely be optimized away. An alternative approach to this is merging Color4 into Vector4 so whether something is a color or vector becomes a matter of interpretion.

**Comment by jvbsl** [comment]
I don't know if this is true for this instances, but it should be:
There is no need forfixed-keyword getting pointers to a struct, should be faster without(if it does not get optimized).

@ahmetsait last time I tested it did not get optimized on .Net Framework 4.5 at least not as good as with pointer arithmetics. But it probably was a special case as well, as I used it for SIMD(and found a Runtime-Bug on the way, which should be fixed in the next version^^).

I still would keep the Color struct and use implicit operators. If with or without pointer arithmetic, I think performance needs to be tested(or outputed assembly code)...

**Comment by jvbsl** [comment]
If we use the implicit operator or something similar we do not need to access "this" and therefore don't need all that __makeref magic but are able to use pointers directly:

```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static unsafe implicit operator Color4(Vector4 vec)
{
    return *(Color4*)(&vec);
}
```
didn't test performance, but it does work. we can perhaps even save the 'dup' on stack for calling that method, as this function can be inlined(tested).

**Comment by varon** [comment]
That seems like a smart trick with the implicit used to avoid fixed there.
We'll need to bench both and check which is fastest.

**Comment by winterhell** [comment]
How does this conversion even works? Color4 has byte components where Vector4 has float components. 
Are you storing the colors in the floats as [0.0 to 1.0] or [0.0 to 255.0]?

**Comment by ahmetsait** [comment]
@winterhell No: https://github.com/opentk/opentk/blob/master/src/OpenTK.Mathematics/Data/Color4.cs

**Comment by varon** [comment]
@winterhell  - `Color` is different to `Color4`

**Comment by winterhell** [comment]
I see, I was under the impression Color4 is OpenTK's idependent of System.Drawing version.
Thanks for the info.

**Comment by MutterOberin** [comment]
I use this for Converting .Nets Colors. This is very slow but not used in critical sections:

```
public static Vector4 ColorToVector4(Color color)
        {
            Vector4 result = Vector4.Zero;

            result.X = color.R / 255.0f;
            result.Y = color.G / 255.0f;
            result.Z = color.B / 255.0f;
            result.W = color.A / 255.0f;

            return result;
        }

        public static Color VectorToColor(Vector4 color)
        {
            return Color.FromArgb((int)(Util.Clamp(color.W) * 255),
                                  (int)(Util.Clamp(color.X) * 255),
                                  (int)(Util.Clamp(color.Y) * 255),
                                  (int)(Util.Clamp(color.Z) * 255));
        }
```

For OpenTK.Color4: It is questionable if it should even exist. If it should, there should be the implicit operator inplace.

**Comment by jvbsl** [comment]
Well for Byte-based Color we need something similar to your solution, we can perhaps optimize
http://lolengine.net/blog/2011/3/20/understanding-fast-float-integer-conversions
But the question is if that even works with C# and is not perhaps even slower.

**Comment by devvoid** [comment]
Turns out I only needed the `fixed` keyword because I was implementing it as a function that uses the `this` keyword - replacing it with an operator makes it unnecessary.

Did a little bit of benchmarking, with the following program. I've never done a benchmark before since I've never worked on a program where speed was a major concern, so if I've done something wrong, please let me know.

```cs
using System;
using System.Diagnostics;
using OpenToolkit.Mathematics;

namespace TKMATHTEST
{
    class Program
    {
        static void Main(string[] args)
        {
            Vector4 basicVector = new Vector4(1.0f, 2.0f, 0.0f, 3.0f);
            float test = 0.0f;

            Stopwatch watch = new Stopwatch();

            watch.Start();

            for(int i = 0; i < 10000000; i++)
            {
                //Convert ten million times
                Color4 convertedVector = (Color4)basicVector;
                test += convertedVector.R;
            }

            watch.Stop();

            Console.WriteLine("Elapsed time: {0}", watch.ElapsedMilliseconds);

            while (true) { }
        }
    }
}
```

The float `test` was added because, for some reason, the performance became significantly worse (about three times slower what it normally is) if there was nothing but a cast in the loop. Best I can figure is that creating a variable that's never used for anything and immediately falls out of scope causes the GC to start faster than usual, which slows it down. Using the variable tricks the GC into thinking it's used for longer than it is, delaying it until after the incredibly-brief test is finished. It skews the numbers by a bit, but not enough to cause concern.

Here's the results.

For jvbsl's suggestion:

```cs
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static unsafe explicit operator Color4(Vector4 v)
{
        return *((Color4*)&v);
}
```

Debug: 363 milliseconds
Release: 38 milliseconds

For varon's suggestion:

```cs
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public unsafe Color4 ToColor4()
{
    var tr = __makeref(this);
    Color4 w = default;
    var trw = __makeref(w);
    *((IntPtr*)&trw) = *((IntPtr*)&tr);
    return __refvalue(trw, Color4);
}
```

Debug: 768 milliseconds
Release: 386 milliseconds

Worth noting that using the `default` keyword in this context requires C# 7.1 or higher.
