### ISSUE TITLE
DebugMessageCallback segfaults upon logging (?)

### ISSUE THREAD

**Issue by PJB3005** [opentk/opentk#880]
### Description

I'm trying to use `DebugMessageCallback` and I found a [pastebin](https://pastebin.com/iEk4PD0R) on Discord that I followed, but There's a segfault when I run `GL.BufferData`, presumably because it's trying to log and the logging is failing.

On Linux with Mono, probably relevant.

### Repro steps

[pastebin](https://pastebin.com/iEk4PD0R) this pastebin, probably.

### Expected behavior

Logs being logged.

### Actual behavior

Segfault

### Related information 

* Operating system: Linux
* SDL or Native backend: I think it's SDL
* What version of OpenTK (Installer, NuGet, Source Code): 3.0.1 from NuGet
* What runtime (.NET Framework, CoreCLR, Mono): Mono 5.16.0
* Workarounds (if any): [Indeed there is one](#issuecomment-455863791)

**Comment by jvbsl** [comment]
Code should look something like the following:
```
ldsfld EntryPoints
ldc.i4 389
ldelem.i
calli debugProc, userParam
```
a simple pseudo IL
or more C# pseudo:
```
var address = EntryPoints[389];
((calli)address)(debugProc, userParam)// did not know how to write that more clearly :D
```

The problem should be anywhere there, as other functions working with calli seems to work. Now question would be if EntryPoints is set correctly or not. And is my guess know is correct. While I tested back then, I used reflection to get the EntryPoints[389] value and used Marshal.GetDelegateForFunctionPointer which did work(at least that's what I remember).
What you could try would be a simple native project using the debug callback(I did the same), which did work just fine for me on any hardware...
So a workaround for you would be the ugly reflection part I mentioned, or waiting for OpenTK 4.0 and see if the issue gets resolved, because the whole marshalling part is completely different and not based on the rewriter anymore..

**Comment by PJB3005** [comment]
Nice suggestion on manually getting the callback with reflection, that worked!

Here's the code I used if some future person runs into this:

```cs
        private void _hijackCallback()
        {
            var type = typeof(GL);
            var entryPoints = (IntPtr[]) type.GetField("EntryPoints", BindingFlags.Static | BindingFlags.NonPublic).GetValue(null);
            var ep = entryPoints[184]; // I did this for the OpenGL4 namespace, this value might be incorrect for others.
            var d = Marshal.GetDelegateForFunctionPointer<DebugMessageCallbackDelegate>(ep);
            d(_debugMessageCallbackInstance, new IntPtr(0x3005));
        }

        private delegate void DebugMessageCallbackDelegate([MarshalAs(UnmanagedType.FunctionPtr)] DebugProc proc,
            IntPtr userParam);
```

**Comment by NogginBops** [comment]
For completeness sake I will link to this great guide on how to get this working cleanly without reflection.
https://gist.github.com/Vassalware/d47ff5e60580caf2cbbf0f31aa20af5d

**Comment by jvbsl** [comment]
as far as I can remember I tried to create a GCHandle but it didn't work

**Comment by NogginBops** [comment]
I do this and it works flawlessly, but that might just be stars aligning for me making it work. But in theory it should work.

**Comment by tyronx** [comment]
@jvbsl same. I followed the guide by @NogginBops but I still get Segfaults for some systems on Linux/Mono. 

@PJB3005 you commented there that you did this for the OpenGL4 namespace. Do you happen to know which entry point it is for the OpenGL namespace?

**Comment by PJB3005** [comment]
@tyronx entry point index is `389`.

**Comment by varon** [comment]
Should be fixed? I've used this extensively without any trouble. (Nvidia) Just have to make sure you've correctly pinned the callback with a GCHandle.
