### ISSUE TITLE
Broken graphics on a multi monitor system

### ISSUE THREAD

**Issue by josmuen** [opentk/opentk#889]
### Description

We successfully moved our project from Tao to OpenTk a few years ago. Now we have an big issue in a multi terminal setup. 3D graphics is not properly drawn and the API concerning textures and lists behaves incorrect. 
Our client workstation contains 2 NVIDA graphic cards (Quadro FX NVS 810/PCIe/SSE2) with 8 output ports each. Currently, 12 monitors are connected.

When we start the same application by using the old Tao OpenGl library, everything works as expected. Tao and OpenTK use the same underlying driver dlls. The driver dlls are updated to most recent version.

### Actual behavior

- Opening a single 3D graphics form on the main screen works properly. Moving the form to another screen causes the graphics to get destroyed.
- Incorrect API behviour: Subsequent calls to _GL.GenLists(1)_ or _GL.GenTextures(1, out ret)_ do not increment their return values as expected. A few calls behave as expected, but at a certain point, the returned values start at 1. It seems, like the driver loses the already registered textures or lists.
- _GL.GetError()_ and the debug ouput do not show any warning or error message. 

### Related information 

* Windows 10
* Native backend
* OpenTK 3.0.1 Nuget
* .NET Framework 4.6.2
* GC: NVIDIA Quadro FX NVS 810/PCIe/SSE2
* OpenGL version: 4.6.0 NVIDIA 412.29
* OpenGL glsl version: 4.60 NVIDIA
* No workaround found

**Comment by varon** [comment]
Thanks for the report, @josmuen.

Certainly sounds like a very interesting bit of software you've got there!

This is very likely going to be fixed by 4.0, as we're moving to GLFW for all of our windowing. You can see this progress in PR #867 .

If it's critical and you can figure out what's causing it, we're happy to accept a patch to fix 3.0+ OpenTK.

**Comment by leezer3** [comment]
What this smells like is that you're moving the window from a monitor managed by card 1 to a monitor managed by card 2.
At this point, it looks to me like it then restarts the list counters / texture counters for the second card. Obviously at this point, your existing references will be invalid.

Does the API behaviour only manifest **after** you've moved onto the second screen?

A workaround thought would be to specifically check whether the index restarts, and if so invalidate all previous list / texture handles. This doesn't address the root of the problem, but presumably you can dynamically recreate these as required?

Might be interesting to try moving back to the orignal monitor too, and see what happens if you don't physically crash?

**Comment by josmuen** [comment]
We tested another scenario.
- The problem remains just with one graphic card (8 ports, 5 connected)
- Opening forms on two of the 5 screens will never show broken graphics. On the other ones, the forms are always destroyed.
- Moving forms around between the 5 screens does't change their state. I.e. broken forms remain broken, correct forms remain correct. If a form gets destroyed, depends on where the form gets opened.

- Another odd behaviour: Activating the debug output by using GL.DebugMessageCallback and GL.DebugMessageControl cause a NullReferenceException internally when calling GL.Disable(EnableCap.Lighting)

**Comment by jvbsl** [comment]
Could it be that there is a problem with using legacy OpenGL. As e.g. Lighting cap was removed from Core 3.1 afaik.
Could you perhaps setup the DebugMessageCallback with help of this one: https://github.com/opentk/opentk/issues/880
Perhaps you'll get debug messages which help in identifieng the problem the driver has(not OpenGL itself, as it often ignores errors...)

**Comment by mikeoverbay** [comment]
I'm good throw this out there...
Could it be that the monitors have different color settings? This can be done according to what I was just reading. Are all your monitors the same brand? If not I'd try to check that they are all running the same color 24 or 32 bit color.

**Comment by varon** [comment]
Should be fixed by 4.x
