### ISSUE TITLE
4.0 Status Update

### ISSUE THREAD

**Issue by markzielinski** [opentk/opentk#900]
Hi,

When do you think 4.0 will be usable to experiment with as a beta?  I'm primarily interested in .NET Core support, especially support for .NET Core 3.0.

Thanks,
Mark

**Comment by devvoid** [comment]
Short answer: As soon as we can get it done.

Long answer: We're getting closer. The two big PRs that 4.0 depends on, the binder and the GLFW-based windowing system, are both coming to a close and should hopefully be done soon. Afterwards, it's just a lot of testing, bugfixing, and also OpenTK.Input, and then a beta should be ready.

Also, questions like these are better saved for our Discord - the issues page is only for bug reports or project coordination.

**Comment by varon** [comment]
@markzielinski  - If you're keen on getting it out the door faster, we'd love some help. The community is really friendly, and we're always happy to assist you if you get stuck.

Contributing in a meaningful way is actually far easier than you might imagine, and at the moment we're really keen on merging all of the little quality-of-life improvements that people wanted in OpenTK 3.0 but couldn't get in due to the the breaking API changes they might have caused.

**Comment by markzielinski** [comment]
Thanks everyone, appreciate the quick update!

**Comment by Ziagl** [comment]
I'm also interested in support for .NET Core 3.0, but currently I'm busy learning OpenTK on .NET. Hope there will be an update soon.

**Comment by jvbsl** [comment]
well it will be done for .Net standard 2, so it will work with .Net Core 3.0 as well. Currently the binder still needs a little addition for some more complex overloads. Then a preview is gonna be published, so it is not to far off
