### ISSUE TITLE
Question about the design of matrix types.

### ISSUE THREAD

**Issue by mizuno-gsinet** [opentk/opentk#922]
### Description

OpenTK has a difference in the design of matrix types than OpenGL as summarized in a table below. 

|  | Works with<br/>column vectors | Works with<br/>row vectors | Column-major | Row-major |
|---|---|---|---|---|
|OpenTK| - |X| - |X|
|OpenGL/GLSL|X| - |X| -† |

† Row-major matrices can be used with the `row_major` qualifier.

OpenTK's matrices are eventually transposed in OpenGL by reinterpreting them as column-major matrices.

I'm not trying to say which is better, but I'm sure that the difference causes a lot of confusion. Why has OpenTK adopted a different design than OpenGL?

Related: #512

**Comment by varon** [comment]
We've been over this in the other issue. **No transposition takes place.  OpenGL does not reinterpret them. We are not transposing anything.**  pass your matrices without transposing them to your shaders and just use `m * v`.  There is no efficiency loss. We do this because of ancient historical reasons from 13 years ago. When the library was first authored it was thought it was a _good idea_ ™, ostensibly because it allowed 1:1 translation of existing DirectX code, probably related to XNA and MonoGame which used to depend upon OpenTK.

From the [OpenGL FAQ](https://www.opengl.org/archives/resources/faq/technical/transformations.htm):

_Column-major versus row-major is purely a notational convention. Note that post-multiplying with column-major matrices produces the same result as pre-multiplying with row-major matrices. The OpenGL Specification and the OpenGL Reference Manual both use column-major notation. You can use any notation, as long as it's clearly stated._

_Sadly, the use of column-major format in the spec and blue book has resulted in endless confusion in the OpenGL programming community. Column-major notation suggests that matrices are not laid out in memory as a programmer would expect._

--

I'm closing this because this kind of 'why' discussion should happen on discord. We'd love for you to come and be a part of our community there:

https://discord.gg/6HqD48s

**Comment by mizuno-gsinet** [comment]
@varon Thank you for the clarification. I'm not going to discuss anything nor trying to change anything. I just asked a fact, why the decision was made in the past. That information should be valuable for understanding the library better.

>**No transposition takes place. OpenGL does not reinterpret them. We are not transposing anything.**

I know that OpenTK nor OpenGL does transposition. I meant that OpenTK's row-major matrices are transposed **as a result** of being interpreted as column-major matrices in OpenGL. I'm sorry if the description was unclear.

**Comment by bikemurt** [comment]
Not to raise this from the dead - but OpenTK storing in row-major format does impact how a game engine might function when a lot of industry standard uses column-major order. For example, in the glTF format matrices are stored in column-major format, such as the inverse bind matrix or general transformation matrices. In shaders, as this thread points out, you simply reverse the order on matrix multiplications. However, when parsing binary data from a gltf file, the order that the matrix components are received are not the "simplest" order. Meaning I need to receive the entire 16 floats, buffer them into an array and then put them into a Matrix4 object as appropriate. This is a small performance loss, since ordinarily you can just process 4 floats at a time (no buffering) and directly insert them into the column-major order matrix.

**Comment by NogginBops** [comment]
Yes, the case where you are given column major matrices, as gltf having to convert them to row major could be a slight performance decrease.

But this shouldn't really be a problem, it's not a lot of processing so the overhead should be quite low. Also for a final game it's good to consider shipping a custom format that stores the data exactly as you need it, as gltf is only a "transfer format" and not meant to be your final model format for a shipping game.

I don't consider this a reason to change to column major matrices.
