### ISSUE TITLE
3.0 Nuget Package update / release

### ISSUE THREAD

**Issue by leezer3** [opentk/opentk#940]
### Description
Not really a bug as such, rather a 'query' :P

Do we have a plan in place for pushing an official released update to 3.0 & the Nuget package (And for that matter for any subsequent patches)?

I've just had a PR to my main repo changing my dependancies to Nuget as opposed to built binaries, and openTK is the primary outlier here.

cc @varon

**Comment by NogginBops** [comment]
My opinion is that this is a good idea. Even if we previously stated that we wouldn't release any more 3.0 release. There has obviously been bugs discovered and they have even been fixed so it feels stupid not to let people into those fixes (if they are using nuget).

That said I don't know the full details of building a 3.0 release and if the complexity there was the reason for the total drop for 3.0 (4.0 is getting a new build system).

**Comment by daerogami** [comment]
IIRC (and the maintenance team can correct me when they see this) the reason is that 4.0 was a major departure from 3.0, almost everything has been rewritten. Since time and resources are  so limited, there hasn't been much interest in maintaining and updating 3.0

**Comment by NogginBops** [comment]
Yeah the 4.0 bindings are indeed rewritten using a new system and windowing/input is now handled using glfw, so no platform dependent implementations.

If anyone knows what is required to put a new build out, please share that and I can do the work to actually make the build (if it's not terribly complicated)

**Comment by varon** [comment]
Building 3.0 is actually super easy (last I did it). The build system works well; just making a release is a manual process rather than automatic.

For 4.0 initially we wanted to try and simplify things. Unfortunately the default tooling for this in netcore wasn't up to the task, which is why we've adopted FAKE 5 for 4.0's build system.

To clarify/echo what @daerogami stated: We're basically happy to help maintain the package for 3.x, but adding/working on it hasn't been our focus. If you guys need a release, just ask and I'm happy to make one.

@leezer3  - would you like me to push a release out?

**Comment by NogginBops** [comment]
I've written a changes summary for the new release (see discord) so you only need to do the build and release it @varon !

**Comment by varon** [comment]
It's live!

https://www.nuget.org/packages/OpenTK/3.1.0

@leezer3 - Would love for you to join us on Discord. Any chance I can persuade you?

**Comment by leezer3** [comment]
Great, thanks :)

Not on Discord (or any other social media for that matter), and don't plan to be.....
WRT to the maintenance concerns, my argument there would be that you've got 100,000+ downloads on Nuget. 
No idea how many of those will see use from the newer version, but for the little effort this seems to have cost us I think it's absolutely worth it.
