### ISSUE TITLE
SIMD support

### ISSUE THREAD

**Issue by Sebmaster** [opentk/opentk#97]
Microsoft just [announced](http://blogs.msdn.com/b/dotnet/archive/2014/04/07/the-jit-finally-proposed-jit-and-simd-are-getting-married.aspx) SIMD support with their new JIT.

It would be nice to explore in how far switching to the provided Vector structs in [Microsoft.Bcl.Simd](https://www.nuget.org/packages/Microsoft.Bcl.Simd) would be feasible.

~~Maybe it's possible to take advantage of the SIMD optimizations even if the OpenTK structs just extend the MS structs, which would also have the added benefit that it would be backwards compatible (I think, didn't look too far into it).~~
No inheritance for structs :(

**Comment by ala53** [comment]
Having looked at the source code to the CLR a bit, perhaps there is a simpler solution: add a [JITIntrinsic] tag to the vectors. Perhaps @terrajobst could chime in on whether that would work provided we have the same memory layout on vectors?

**Comment by varon** [comment]
I'm going to close this, because the direction of SIMD appears to have changed quite a bit.

This is something we'd definitely like to look at, but it needs careful re-evaluation with our goal of targeting a .net standard or .net core version. It's also something we won't have the manpower to do without a significant external contribution.

Here's a quick reference to #500, which is similar, but not as revolutionary.
