### ISSUE TITLE
Provide OpenGL bindings as standalone library.

### ISSUE THREAD

**Issue by softwareantics** [opentk/opentk#982]
Most OpenGL C# bindings don't follow C# standards, for example:

`GL.BindBuffer(BufferTarget.ArrayBuffer, id);`

will end up looking like this:

`GL.BindBuffer(GL_ARRAY_BUFFER, id);`

Personally, I hate the latter and would really like OpenTK to have a separate release with just the OpenGL bindings, separating from windowing, input, audio, etc.

What difficulties lie ahead if we we're to implement such a thing? Will it support .NET Standard 2.0?

**Comment by realvictorprm** [comment]
@mtosoftware Can you clarify what you mean? OpenTK has seperate enums so `BufferTarget.ArrayBuffer` would be used, not `GL_ARRAY_BUFFER`.

**Comment by mtosoftware** [comment]
> 
> 
> @mtosoftware Can you clarify what you mean? OpenTK has seperate enums so `BufferTarget.ArrayBuffer` would be used, not `GL_ARRAY_BUFFER`.

I mean that other OpenGL bindings (SharpGL, OpenGL.Net, etc) mostly use constant variables such as `GL_ARRAY_BUFFER` whereas OpenTK uses the much more C# style friendly `BufferTarget.ArrayBuffer`. I'm wondering if the bindings of OpenGL will be able to be downloaded as a NuGet package or perhaps a separate release for the release of 4.0?

The sole reason behind my asking is because I like how OpenTK's bindings of OpenGL feel, things like enumerations are used in-place of constants. It just feels much more C# friendly.

**Comment by realvictorprm** [comment]
Ah I see, ok.
cc @varon

**Comment by varon** [comment]
Thanks for the cc @realvictorprm .

As long as the bindings are initialized correctly (via loading the endpoints) it should work in whatever windowing you're using.

For 4.0 the packages are intended to be split up a bit more than the monster package that is 3.0.

**Comment by mtosoftware** [comment]
> As long as the bindings are initialized correctly (via loading the endpoints) it should work in whatever windowing you're using.

@varon, sorry, could you provide me with a bit more of an explanation on how to accomplish this?

**Comment by utkumaden** [comment]
Join the discord, people are more likely to help you there, and faster.
https://discord.gg/6HqD48s

**Comment by varon** [comment]
Solved by 4.x
