### ISSUE TITLE
Consider publishing a separate assembly for mono/mac platforms

### ISSUE THREAD

**Issue by glopesdev** [opentk/opentk#994]
I have just come back to updating OpenTK dependencies and prototype the new 4.0 version and just realized the full extent and implication of the decisions around the namespace change.

I believe this is a profound mistake for this project, but one which I hope we can still prevent. Allow me to elaborate:

OpenTK has a 14+ year history, the first commit harks back to 2006, when I first started programming professionally. Since then, I and many other developers have relied on it systematically for years and years. The presence and impact of the OpenTK in the community is sheer testament to this. This impact has led OpenTK to be appropriated by the mono project, and consequently official bits of documentation are now lingering in Microsoft's own support website: https://docs.microsoft.com/en-us/dotnet/api/opentk?view=xamarin-ios-sdk-12

I have just unrolled the events of the past year and I understand how painful it must be for the maintainers to have undertaken the decision to change the namespace. I don't want to reopen old wounds, but in the name of protecting this community, I believe that I must.

This is not about binary and source compatibility anymore, the sheer impact and extent of the OpenTK brand has now implications for SEO when people look for help. Documentation will be far more important than find/replace operations, especially for new users who will establish and represent the future of OpenTK.

I know Xamarin feels like the big shark who are entitled to hold their ground and just shut off, but on behalf of at least my community of indirect OpenTK users (extensive in open-science and visualization) I urge you not to concede this ground.

If I understand correctly, the problem stems from a particular distribution of OpenTK, the one that clashes with Mono/Xamarin official distro that is shipped with their platform. If this is the case, why not generate a specific distribution _**just for this scenario**_ until they come around and decide to remove the OpenTK assemblies, as per their [XAMCORE audit](https://github.com/xamarin/xamarin-macios/issues/5107
)?

The rationale is that if this use case didn't work before, then there are really no users which are depending on it working at the moment. This means that if you introduce a renamed OpenTK just for Xamarin, you will not harm any existing user base and more importantly, by keeping the _root_ namespace intact, you will keep the important documentation identity for OpenTK. Again this is NOT just about root namespace / child namespace. For non-English speaking users OpenTK is a completely different word from OpenToolkit, and should not be changed lightly. Especially changing the name of the assembly and nuget packages is a mistake, the ID change will take years to sort out.

The OpenTK community is not huge and marketing / communication is bandwidth limited so this risks fragmenting it even further into oblivion. _Please do not do this._

As for implementation, given that code generation tools are starting to be incorporated extensively in the OpenTK build process, it doesn't seem like it would be too hard to automate the publishing process for this temporary platform release. I am happy to help directly with this and allocate however many work hours are needed for me to familiarize myself with the build pipeline and make it happen.

As for a proposal for what name to use for the specific deployment NuGet / namespace for Xamarin platforms, I suggest: **OpenTK.Xamarin**

In light of everything that has happened, I feel it is only right, but would accept better suggestions.

**Comment by varon** [comment]
Thank you for posting this @glopesdev. We really appreciate this feedback.

The decision was made over a year ago because Xamarin refused to meet us half way, shutting down discussion and refusing to compromise (despite our best efforts). We've stuck with it until now, as we still believe it's the best decision we can make.

It's hard to respond to such good criticisms as there's no clear right answer; everyone loses out in some way or another despite it not being our fault at all. In the OpenTK project we have and always will try to put our users first. If we did use a separate assembly (with different namespaces) on Xamarin platforms, it becomes very non-trivial to have code written against one assembly work against another (without recompilation). This situation dramatically complicates the lives of our users, which is why we want to take every step we can to avoid it.

We can definitely keep the package Ids as OpenTK, as there's no necessary relation between package IDs and namespaces, and you're absolutely correct in pointing out how silly it would be to eschew our mindshare and package download statistics.

You're also right about OpenTK and OpenToolkit, along with SEO. It's a fair point that hasn't been raised yet, and something we should definitely consider.

`Open.TK` perhaps? (@frederikja163  @jvbsl  @PJB3005 )

**Comment by glopesdev** [comment]
Actually, there may be a trivial fix to this. In the .NET runtime, the unique type identifier is composed of the full type name (namespace + name) AND the qualified assembly name.

It shouldn't be a problem at all to keep the OpenTK namespace, as long as the assembly name is different just for Xamarin.Mac deployments.

The report from Bugzilla seems to confirm this: https://xamarin.github.io/bugzilla-archives/18/18575/bug.html (check the end of the first description, the guy fixed it just changing the DLL name).

I don't think you guys need to change the namespace at all, just the assembly name (e.g. to **OpenTK.Xamarin.dll**). That way all the code will stay the same, and maybe users will need to use a couple of assembly reference redirects and have an extra project for targeting Xamarin (but using exact same source code), which is way more trivial. Is there an obvious blocker to this approach that I'm missing?

**Comment by varon** [comment]
Resolved
