### ISSUE TITLE
Samples for simple recording

### ISSUE THREAD

**Issue by BarryOCathain** [opentk/opentk#998]
This is more of a request for information than anything.

I've been digging at this library for a while to do audio recording on the raspberry pi.

I've had a look at the parrot example in the mono version, and I've searched around but I've been unable to find a really simple, recording example. 

Would this be something that could be provided? Or is there already a decent set of examples somewhere that I've missed?

Cheers.

**Comment by NogginBops** [comment]
This is a somewhat old issue but better late than never, right?

There actually exists such an example in the latest source!
https://github.com/opentk/opentk/blob/master/OpenALTest/ALTest.cs#L79
It just allocates a 4s buffer, opens a capture device and records audio from that.

Going to consider this issue fixed with this. 🙂
